# Generated by Django 6.0.4 on 2026-05-19 22:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(default='Banco do Brasil', max_length=50)),
                ('agencia', models.CharField(blank=True, max_length=20, null=True, verbose_name='Agência')),
                ('conta', models.CharField(max_length=50, verbose_name='Número da Conta')),
                ('dv', models.CharField(max_length=5, verbose_name='Dígito Verificador')),
            ],
            options={
                'verbose_name': 'Conta Bancária',
                'verbose_name_plural': 'Contas Bancárias',
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Razão Social / Nome')),
                ('cnpj', models.CharField(max_length=20, unique=True, verbose_name='CNPJ')),
                ('sigla', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sigla / Nome Curto')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço Completo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail de Contato')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Local')),
                ('sigla', models.CharField(blank=True, max_length=20, null=True, verbose_name='Sigla do Setor')),
                ('responsavel', models.CharField(blank=True, max_length=100, null=True, verbose_name='Responsável pelo Local')),
            ],
            options={
                'verbose_name': 'Localização',
                'verbose_name_plural': 'Localizações',
            },
        ),
        migrations.CreateModel(
            name='OrigemDoacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Instituição')),
                ('sigla', models.CharField(max_length=20, verbose_name='Sigla')),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True, verbose_name='CNPJ')),
            ],
            options={
                'verbose_name': 'Origem da Doação',
                'verbose_name_plural': 'Origens das Doações',
            },
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=100, verbose_name='Nº do Processo')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição do Objeto')),
                ('origem', models.CharField(choices=[('IFAM Reitoria', 'IFAM Reitoria'), ('FAEPI', 'FAEPI'), ('OUTRA', 'Outra Pessoa Jurídica (PJ)')], default='FAEPI', max_length=100, verbose_name='Origem do Processo')),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='ProjetoPDI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Projeto')),
                ('convenio', models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message='O convênio deve seguir o padrão: XXXX/ANO (Ex: 0013/2022)', regex='^\\d{4}/\\d{4}$')], verbose_name='Número do Convênio')),
                ('termo_de_convenio', models.FileField(blank=True, null=True, upload_to='convenios/termos/', verbose_name='Termo de Convênio (PDF)')),
                ('convenente', models.CharField(default='IFAM', max_length=100, verbose_name='Convenente')),
                ('interveniente', models.CharField(default='FAEPI', max_length=100, verbose_name='Interveniente')),
                ('financiadores', models.TextField(help_text='Razão social dos financiadores', verbose_name='Concedentes / Financiador(es)')),
                ('vigencia_inicio', models.DateField(verbose_name='Início da Vigência Geral')),
                ('vigencia_fim', models.DateField(verbose_name='Fim da Vigência Geral')),
                ('plano_inicio', models.DateField(verbose_name='Início do Plano de Trabalho')),
                ('plano_fim', models.DateField(verbose_name='Fim do Plano de Trabalho')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Projeto PDI',
                'verbose_name_plural': 'Projetos PDI',
            },
        ),
        migrations.CreateModel(
            name='TermoAditivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, verbose_name='Número do Aditivo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Objeto da Alteração')),
                ('nova_data_fim', models.DateField(verbose_name='Nova Data de Término (Se houver prorrogação)')),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='convenios/aditivos/', verbose_name='Documento em PDF')),
                ('data_assinatura', models.DateField(verbose_name='Data de Assinatura')),
            ],
            options={
                'verbose_name': 'Termo Aditivo',
                'verbose_name_plural': 'Termos Aditivos',
            },
        ),
        migrations.CreateModel(
            name='TipoProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Tipo de Processo')),
            ],
        ),
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, verbose_name='Número da NF')),
                ('serie', models.CharField(blank=True, max_length=10, null=True, verbose_name='Série')),
                ('chave_acesso', models.CharField(blank=True, max_length=44, null=True, unique=True, verbose_name='Chave de Acesso')),
                ('data_emissao', models.DateField(verbose_name='Data de Emissão')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Total')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_fiscais', to='cadastros.fornecedor')),
            ],
            options={
                'verbose_name': 'Nota Fiscal',
                'verbose_name_plural': 'Notas Fiscais',
            },
        ),
    ]
