# Generated by Django 6.1.1 on 2026-09-11 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
        ('incorporacao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='termo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_fiscais', to='incorporacao.termodoacao', verbose_name='Termo de Doação Vinculado'),
        ),
        migrations.AddField(
            model_name='parcela',
            name='conta_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcelas_pagas', to='cadastros.contabancaria', verbose_name='Conta Bancária Pagadora'),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Vínculo institucional exclusivo do Administrador do Sistema.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pessoa_fisica', to=settings.AUTH_USER_MODEL, verbose_name='Conta de Acesso (User)'),
        ),
        migrations.AddField(
            model_name='perfilterceirizado',
            name='pessoa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_terceirizado', to='cadastros.pessoafisica'),
        ),
        migrations.AddField(
            model_name='perfilservidor',
            name='pessoa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_servidor', to='cadastros.pessoafisica'),
        ),
        migrations.AddField(
            model_name='perfilcolaboradorexterno',
            name='pessoa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_colaborador_externo', to='cadastros.pessoafisica'),
        ),
        migrations.AddField(
            model_name='perfilaluno',
            name='pessoa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_aluno', to='cadastros.pessoafisica'),
        ),
        migrations.AddField(
            model_name='dadobancario',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dados_bancarios', to='cadastros.pessoafisica'),
        ),
        migrations.AddField(
            model_name='planodetrabalho',
            name='indicadores',
            field=models.ManyToManyField(blank=True, related_name='planos_trabalho', to='cadastros.indicadorresultado'),
        ),
        migrations.AddField(
            model_name='planodetrabalho',
            name='termo_homologador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos_homologados', to='cadastros.instrumentojuridicobase', verbose_name='Termo Homologador'),
        ),
        migrations.AddField(
            model_name='membroequipept',
            name='plano_trabalho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipe', to='cadastros.planodetrabalho'),
        ),
        migrations.AddField(
            model_name='macroentrega',
            name='plano_trabalho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='macroentregas', to='cadastros.planodetrabalho'),
        ),
        migrations.AddField(
            model_name='historicalrubricaorcamentariapt',
            name='plano_trabalho',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cadastros.planodetrabalho'),
        ),
        migrations.AddField(
            model_name='cronogramadesembolso',
            name='plano_trabalho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desembolsos', to='cadastros.planodetrabalho'),
        ),
        migrations.AddField(
            model_name='atividadeplanoacao',
            name='plano_trabalho',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='cadastros.planodetrabalho'),
        ),
        migrations.AddField(
            model_name='processo',
            name='conta_bancaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos', to='cadastros.contabancaria', verbose_name='Conta Bancária Pagadora'),
        ),
        migrations.AddField(
            model_name='projetopdi',
            name='concedente',
            field=models.ForeignKey(blank=True, help_text='Quem está financiando a demanda principal (ex: Empresa ou EMBRAPII no caso de PDC).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_concedidos', to='cadastros.pessoajuridica', verbose_name='Concedente (Empresa/Agência)'),
        ),
        migrations.AddField(
            model_name='projetopdi',
            name='coordenador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_coordenados', to='cadastros.pessoafisica', verbose_name='Coordenador do Projeto'),
        ),
        migrations.AddField(
            model_name='projetopdi',
            name='programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_vinculados', to='cadastros.programa', verbose_name='Programa Associado'),
        ),
        migrations.AddField(
            model_name='processo',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processos', to='cadastros.projetopdi'),
        ),
        migrations.AddField(
            model_name='planodetrabalho',
            name='projeto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planos_trabalho', to='cadastros.projetopdi'),
        ),
        migrations.AddField(
            model_name='membroequipe',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipe_pdi', to='cadastros.projetopdi'),
        ),
        migrations.AddField(
            model_name='historicotransicaofase',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico_fases', to='cadastros.projetopdi'),
        ),
        migrations.AddField(
            model_name='historicalplanodetrabalho',
            name='projeto',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cadastros.projetopdi'),
        ),
        migrations.AddField(
            model_name='historicalcotabolsapt',
            name='projeto',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cadastros.projetopdi'),
        ),
        migrations.AddField(
            model_name='cotabolsapt',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotas_bolsas', to='cadastros.projetopdi'),
        ),
        migrations.AddField(
            model_name='contabancaria',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas', to='cadastros.projetopdi'),
        ),
        migrations.AddField(
            model_name='bolsistaprojeto',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bolsistas', to='cadastros.projetopdi'),
        ),
        migrations.AddField(
            model_name='rubricaorcamentariapt',
            name='plano_trabalho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubricas', to='cadastros.planodetrabalho'),
        ),
        migrations.AddField(
            model_name='termoaditivo',
            name='instrumento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aditivos', to='cadastros.instrumentojuridicobase'),
        ),
        migrations.AddField(
            model_name='termobolsa',
            name='cota_pt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='termos_vinculados', to='cadastros.cotabolsapt'),
        ),
        migrations.AddField(
            model_name='termobolsa',
            name='pessoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='termos_bolsa', to='cadastros.pessoafisica'),
        ),
        migrations.AddField(
            model_name='parcela',
            name='termo_bolsa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='cadastros.termobolsa'),
        ),
        migrations.AddField(
            model_name='termoencerramento',
            name='instrumento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encerramento', to='cadastros.instrumentojuridicobase'),
        ),
        migrations.AddField(
            model_name='instrumentojuridicobase',
            name='tipo_instrumento_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='cadastros.tipoinstrumentojuridico', verbose_name='Tipo de Instrumento (Parametrizado)'),
        ),
        migrations.AddField(
            model_name='processo',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.tipoprocesso', verbose_name='Tipo de Processo'),
        ),
        migrations.AddField(
            model_name='acordodeparceria',
            name='concedente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acordos_concedidos', to='cadastros.pessoajuridica', verbose_name='Concedente (Empresa/Agência)'),
        ),
        migrations.AddField(
            model_name='acordodeparceria',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acordos_parceria', to='cadastros.projetopdi', verbose_name='Projeto Mestre'),
        ),
        migrations.AddField(
            model_name='convenio',
            name='concedente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termos_concedidos', to='cadastros.pessoajuridica', verbose_name='Concedente (Empresa/Agência)'),
        ),
        migrations.AddField(
            model_name='convenio',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='convenios', to='cadastros.projetopdi', verbose_name='Projeto Mestre'),
        ),
        migrations.AddField(
            model_name='termocooperacao',
            name='concedente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termos_cooperacao_concedidos', to='cadastros.pessoajuridica', verbose_name='Parceiro'),
        ),
        migrations.AddField(
            model_name='programa',
            name='termo_cooperacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programas', to='cadastros.termocooperacao', verbose_name='Termo de Cooperação'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_fiscais', to='cadastros.fornecedor'),
        ),
        migrations.AddField(
            model_name='projetopdi',
            name='interveniente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_intervenientes', to='cadastros.fundacaoapoio', verbose_name='Interveniente (Fundação de Apoio)'),
        ),
        migrations.AddField(
            model_name='convenio',
            name='interveniente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interveniente_em', to='cadastros.fundacaoapoio', verbose_name='Interveniente'),
        ),
        migrations.AddField(
            model_name='acordodeparceria',
            name='interveniente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interveniente_em_acordo', to='cadastros.fundacaoapoio', verbose_name='Interveniente'),
        ),
        migrations.AddField(
            model_name='termocooperacao',
            name='convenente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termos_cooperacao_conveniados', to='cadastros.ict', verbose_name='ICT'),
        ),
        migrations.AddField(
            model_name='projetopdi',
            name='convenente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_conveniados', to='cadastros.ict', verbose_name='Convenente (ICT Executora)'),
        ),
        migrations.AddField(
            model_name='convenio',
            name='convenente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='convenente_em', to='cadastros.ict', verbose_name='Convenente'),
        ),
        migrations.AddField(
            model_name='acordodeparceria',
            name='convenente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='convenente_em_acordo', to='cadastros.ict', verbose_name='Convenente'),
        ),
        migrations.AlterUniqueTogether(
            name='planodetrabalho',
            unique_together={('projeto', 'versao')},
        ),
        migrations.AlterUniqueTogether(
            name='membroequipe',
            unique_together={('projeto', 'usuario')},
        ),
        migrations.AlterUniqueTogether(
            name='parcela',
            unique_together={('termo_bolsa', 'numero')},
        ),
        migrations.AddConstraint(
            model_name='instrumentojuridicobase',
            constraint=models.UniqueConstraint(condition=models.Q(('ano__isnull', False), ('sequencial__isnull', False)), fields=('tipo_instrumento', 'sequencial', 'ano'), name='unique_seq_ano_por_tipo'),
        ),
        migrations.AlterUniqueTogether(
            name='notafiscal',
            unique_together={('numero', 'fornecedor')},
        ),
    ]
