# Generated by Django 6.0.4 on 2026-05-19 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
        ('incorporacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='termo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_fiscais', to='incorporacao.termodoacao', verbose_name='Termo de Doação Vinculado'),
        ),
        migrations.AddField(
            model_name='processo',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processos', to='cadastros.projetopdi'),
        ),
        migrations.AddField(
            model_name='contabancaria',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas', to='cadastros.projetopdi'),
        ),
        migrations.AddField(
            model_name='termoaditivo',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aditivos', to='cadastros.projetopdi'),
        ),
        migrations.AddField(
            model_name='processo',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.tipoprocesso', verbose_name='Tipo de Processo'),
        ),
        migrations.AlterUniqueTogether(
            name='notafiscal',
            unique_together={('numero', 'fornecedor')},
        ),
    ]
