# Generated by Django 6.0.4 on 2026-05-20 23:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_projetopdi_processo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetopdi',
            name='Processo',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='O processo IFAM deve seguir o padrão: 23443.XXXXXX/ANO-XX', regex='^23443\\.\\d{6}/\\d{4}-\\d{2}$')], verbose_name='Processo de Contratação do Projeto (IFAM)'),
        ),
    ]
