# Generated by Django 6.1.1 on 2026-09-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_seed_tipos_instrumentos_juridicos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentojuridicobase',
            name='numero',
            field=models.CharField(default='N/A', max_length=50, unique=True, verbose_name='Número do Instrumento'),
            preserve_default=False,
        ),
    ]
