# Generated by Django 6.1.1 on 2026-09-12 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_alter_instrumentojuridicobase_numero'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='instrumentojuridicobase',
            name='unique_seq_ano_por_tipo',
        ),
        migrations.AlterUniqueTogether(
            name='instrumentojuridicobase',
            unique_together={('tipo_instrumento_fk', 'numero', 'ano')},
        ),
        migrations.AlterField(
            model_name='instrumentojuridicobase',
            name='ano',
            field=models.PositiveIntegerField(default=2026, verbose_name='Ano'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instrumentojuridicobase',
            name='numero',
            field=models.PositiveIntegerField(verbose_name='Número'),
        ),
        migrations.RemoveField(
            model_name='instrumentojuridicobase',
            name='sequencial',
        ),
    ]
