# Generated by Django 6.0.4 on 2026-05-20 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_alter_projetopdi_processo'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetopdi',
            name='projeto',
            field=models.CharField(blank=True, help_text="Campo opcional para nomear o projeto de forma resumida (ex: 'Projeto de Robótica').", max_length=50, null=True, verbose_name='Projeto'),
        ),
        migrations.AlterField(
            model_name='projetopdi',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome Completo do Projeto'),
        ),
    ]
