# Generated by Django 6.0.4 on 2026-06-19 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_projetopdi_projeto_alter_projetopdi_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_convenio', models.CharField(max_length=50, unique=True, verbose_name='Número do Convênio')),
                ('objeto', models.TextField(blank=True, null=True, verbose_name='Objeto / Descrição')),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Convênio',
                'verbose_name_plural': 'Convênios',
            },
        ),
        migrations.CreateModel(
            name='InstituicaoParceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Instituição')),
                ('sigla', models.CharField(max_length=20, unique=True)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
            ],
            options={
                'verbose_name': 'Instituição Parceira',
                'verbose_name_plural': 'Instituições Parceiras',
            },
        ),
        migrations.AddField(
            model_name='projetopdi',
            name='convenio_oficial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_pdi', to='cadastros.convenio', verbose_name='Convênio Oficial (Estruturado)'),
        ),
        migrations.AddField(
            model_name='convenio',
            name='instituicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='convenios', to='cadastros.instituicaoparceira'),
        ),
    ]
