# Generated by Django 6.0.7 on 2026-07-30 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_convenio_instituicaoparceira_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='projetopdi',
            old_name='Processo',
            new_name='processo',
        ),
        migrations.CreateModel(
            name='BolsistaProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('rg', models.CharField(max_length=30, verbose_name='RG')),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('funcao', models.CharField(help_text='Ex: Desenvolvedor Backend, Pesquisador', max_length=100)),
                ('termo_bolsa', models.CharField(max_length=50, verbose_name='Termo de Bolsa nº')),
                ('data_inicio', models.DateField(verbose_name='Início da Contratação')),
                ('data_fim', models.DateField(verbose_name='Fim da Contratação')),
                ('carga_horaria_total', models.PositiveIntegerField(verbose_name='Carga Horária Total')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bolsistas', to='cadastros.projetopdi')),
            ],
        ),
        migrations.CreateModel(
            name='MembroEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('COORDENADOR', 'Coordenador do Projeto'), ('GESTOR', 'Gestor de Projeto'), ('ANALISTA', 'Analista Integrador'), ('AUX_ADM', 'Auxiliar Administrativo')], max_length=15)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipe_pdi', to='cadastros.projetopdi')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membro da Equipe',
                'verbose_name_plural': 'Membros da Equipe',
                'db_table': 'argus_membro_equipe',
                'unique_together': {('projeto', 'usuario')},
            },
        ),
    ]
