# Generated by Django 6.0.7 on 2026-07-30 00:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0009_alter_projetopdi_processo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetopdi',
            name='processo',
            field=models.CharField(blank=True, db_column='Processo', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='O processo IFAM deve seguir o padrão: 23443.XXXXXX/ANO-XX', regex='^23443\\.\\d{6}/\\d{4}-\\d{2}$')], verbose_name='Processo de Contratação do Projeto (IFAM)'),
        ),
    ]
