# Generated by Django 6.0.7 on 2026-07-30 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0010_alter_projetopdi_processo'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetopdi',
            name='arquivo_plano_trabalho',
            field=models.FileField(blank=True, null=True, upload_to='projetos/planos_trabalho/', verbose_name='Plano de Trabalho Vigente (PDF)'),
        ),
        migrations.CreateModel(
            name='AtividadePlanoAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, verbose_name='Item (Ex: 7.1)')),
                ('descricao', models.TextField(verbose_name='Descrição da Atividade')),
                ('periodo_inicio', models.DateField()),
                ('periodo_fim', models.DateField()),
                ('papeis_exclusivos', models.CharField(blank=True, help_text='Funções exclusivas separadas por vírgula (ex: Coordenador, Auxiliar Administrativo). Deixe em branco para acesso de todos os bolsistas.', max_length=255)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades_plano', to='cadastros.projetopdi')),
            ],
        ),
    ]
