# Generated by Django 6.0.7 on 2026-07-30 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0011_projetopdi_arquivo_plano_trabalho_atividadeplanoacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='CotaBolsaPT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil_funcao', models.CharField(max_length=150, verbose_name='Perfil/Função (Ex: Pesquisador Sênior)')),
                ('quantidade_vagas', models.PositiveIntegerField(default=1, verbose_name='Quantidade de Vagas')),
                ('parcelas_previstas', models.PositiveIntegerField(verbose_name='Total de Parcelas Previstas')),
                ('valor_global_previsto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Global Previsto (R$)')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotas_bolsas', to='cadastros.projetopdi')),
            ],
        ),
        migrations.CreateModel(
            name='TermoBolsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bolsista_nome', models.CharField(max_length=255)),
                ('bolsista_cpf', models.CharField(max_length=14)),
                ('numero_termo', models.CharField(max_length=50, verbose_name='Número do Termo de Bolsa/Aditivo')),
                ('vigencia_inicio', models.DateField()),
                ('vigencia_fim', models.DateField()),
                ('quantidade_parcelas', models.PositiveIntegerField(verbose_name='Parcelas Contratadas (Neste Termo)')),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Parcela (R$)')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('ENCERRADO', 'Encerrado (Fim do Prazo)'), ('SUBSTITUIDO', 'Substituído (Evasão/Troca)'), ('CANCELADO', 'Cancelado')], default='ATIVO', max_length=20)),
                ('cota_pt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='termos_vinculados', to='cadastros.cotabolsapt')),
            ],
        ),
    ]
