# Generated by Django 6.0.7 on 2026-07-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0013_migrar_dados_bolsistas'),
    ]

    operations = [
        migrations.AddField(
            model_name='contabancaria',
            name='fonte_recurso',
            field=models.CharField(default='Não Identificada', help_text='Ex: EMBRAPII, SEBRAE, Empresa Parceira', max_length=100, verbose_name='Fonte do Recurso'),
            preserve_default=False,
        ),
    ]
