# Generated by Django 6.0.7 on 2026-07-30 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0014_contabancaria_fonte_recurso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividadeplanoacao',
            name='papeis_exclusivos',
        ),
        migrations.RemoveField(
            model_name='atividadeplanoacao',
            name='periodo_fim',
        ),
        migrations.RemoveField(
            model_name='atividadeplanoacao',
            name='periodo_inicio',
        ),
        migrations.AddField(
            model_name='atividadeplanoacao',
            name='entregaveis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atividadeplanoacao',
            name='justificativa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atividadeplanoacao',
            name='mes_fim_relativo',
            field=models.PositiveIntegerField(default=1, help_text='Mês de fim (Ex: 9)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atividadeplanoacao',
            name='mes_inicio_relativo',
            field=models.PositiveIntegerField(default=2026, help_text='Mês de início (Ex: 1)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atividadeplanoacao',
            name='nome',
            field=models.CharField(default=1, max_length=255, verbose_name='Nome da Atividade'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='atividadeplanoacao',
            name='numero',
            field=models.CharField(max_length=10, verbose_name='Item (Ex: 1)'),
        ),
    ]
