# Generated by Django 6.0.7 on 2026-07-31 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0015_remove_atividadeplanoacao_papeis_exclusivos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.IntegerField(default=1, verbose_name='Versão do Plano (Aditivos)')),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='projetos/planos_trabalho/', verbose_name='Plano de Trabalho Vigente (PDF)')),
                ('data_inicio', models.DateField(verbose_name='Início do Plano de Trabalho')),
                ('data_fim', models.DateField(verbose_name='Fim do Plano de Trabalho')),
                ('valor_global', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor Global (R$)')),
                ('aporte_empresa', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Aporte Empresa (R$)')),
                ('aporte_embrapii', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Aporte EMBRAPII (R$)')),
                ('aporte_sebrae', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Aporte SEBRAE (R$)')),
                ('aporte_contrapartida', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Contrapartida (R$)')),
                ('projeto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='planotrabalho', to='cadastros.projetopdi')),
            ],
            options={
                'verbose_name': 'Plano de Trabalho',
                'verbose_name_plural': 'Planos de Trabalho',
            },
        ),
        migrations.CreateModel(
            name='RubricaOrcamentariaPT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('RH_DIRETO', 'RH Direto'), ('RH_INDIRETO', 'RH Indireto'), ('SERVICOS_TERCEIROS', 'Serviços Técnicos de Terceiros'), ('MATERIAIS', 'Materiais de Consumo'), ('EQUIPAMENTOS', 'Equipamentos e Software'), ('OBRAS', 'Obras Civis'), ('VIAGENS', 'Viagens / Diárias'), ('ISS', 'Impostos (ISS)'), ('DOAS', 'Custos DOAS (FAEPI)'), ('RESERVA', 'Fundo de Reserva'), ('OUTROS', 'Outros Correlatos')], max_length=50, verbose_name='Categoria / Dispêndio')),
                ('valor_previsto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Previsto (R$)')),
                ('fonte_recurso', models.CharField(choices=[('EMPRESA', 'Empresa'), ('EMBRAPII', 'EMBRAPII'), ('SEBRAE', 'SEBRAE'), ('CONTRAPARTIDA', 'Contrapartida ICT')], max_length=50, verbose_name='Fonte do Recurso')),
                ('plano_trabalho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubricas', to='cadastros.planotrabalho')),
            ],
            options={
                'verbose_name': 'Rubrica Orçamentária',
                'verbose_name_plural': 'Rubricas Orçamentárias',
            },
        ),
    ]
