# Generated by Django 6.0.7 on 2026-07-31 00:34

from django.db import migrations

def migrate_plano_trabalho(apps, schema_editor):
    ProjetoPDI = apps.get_model('cadastros', 'ProjetoPDI')
    PlanoTrabalho = apps.get_model('cadastros', 'PlanoTrabalho')

    for projeto in ProjetoPDI.objects.all():
        if projeto.plano_inicio and projeto.plano_fim:
            PlanoTrabalho.objects.create(
                projeto=projeto,
                data_inicio=projeto.plano_inicio,
                data_fim=projeto.plano_fim,
                arquivo_pdf=projeto.arquivo_plano_trabalho,
                versao=1,
                valor_global=0.00,
                aporte_empresa=0.00,
                aporte_embrapii=0.00,
                aporte_sebrae=0.00,
                aporte_contrapartida=0.00
            )

class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0016_planotrabalho_rubricaorcamentariapt'),
    ]

    operations = [
        migrations.RunPython(migrate_plano_trabalho),
    ]
