# Generated by Django 6.0.7 on 2026-07-31 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0017_migrate_plano_trabalho_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projetopdi',
            name='arquivo_plano_trabalho',
        ),
        migrations.RemoveField(
            model_name='projetopdi',
            name='plano_fim',
        ),
        migrations.RemoveField(
            model_name='projetopdi',
            name='plano_inicio',
        ),
    ]
