# Generated by Django 6.0.7 on 2026-07-31 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0018_remove_projetopdi_arquivo_plano_trabalho_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubricaorcamentariapt',
            name='descricao',
            field=models.CharField(default='', max_length=255, verbose_name='Descrição do Item'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rubricaorcamentariapt',
            name='categoria',
            field=models.CharField(choices=[('I', 'I - Programas de Computador ou Equipamentos'), ('II', 'II - Aquisição, Implantação, Ampliação ou Modernização de laboratório de P&D'), ('III.1', 'III.1 - Recursos Humanos Diretos'), ('III.2', 'III.2 - Recursos Humanos Indiretos'), ('IV', 'IV - Serviço de Terceiros Técnicos'), ('V', 'V - Material de Consumo'), ('VI.1', 'VI.1 - Treinamentos'), ('VI.2', 'VI.2 - Livros e Periódicos'), ('VI.4', 'VI.4 - Viagens'), ('VI.5', 'VI.5 - ISS'), ('VI.6', 'VI.6 - Outros Correlatos'), ('VII.1', 'VII.1 - Custos FAEPI - DOA'), ('VII.2', 'VII.2 - Constituição de Reserva (IFAM)')], max_length=50, verbose_name='Categoria / Dispêndio'),
        ),
    ]
