# Generated by Django 6.0.7 on 2026-07-31 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0019_rubricaorcamentariapt_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubricaorcamentariapt',
            name='descricao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição do Item'),
        ),
    ]
