# Generated by Django 6.0.7 on 2026-07-31 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0020_alter_rubricaorcamentariapt_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubricaorcamentariapt',
            name='categoria',
            field=models.CharField(choices=[('I', 'I - Programas de Computador ou Equipamentos'), ('II', 'II - Aquisição, Implantação, Ampliação ou Modernização de laboratório de P&D'), ('III', 'III - Recursos Humanos Diretos e Indiretos'), ('IV', 'IV - Serviço de Terceiros Técnicos'), ('V', 'V - Material de Consumo'), ('VI', 'VI - Outros Dispêndios Correlatos'), ('VII', 'VII - Custos Incorridos (DOAS/Reserva)')], max_length=50, verbose_name='Categoria / Dispêndio'),
        ),
    ]
