# Generated by Django 6.0.7 on 2026-07-31 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0021_alter_rubricaorcamentariapt_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotabolsapt',
            name='atividades_vinculadas',
            field=models.ManyToManyField(blank=True, related_name='cotas_vinculadas', to='cadastros.atividadeplanoacao', verbose_name='Atividades do Escopo (O que este perfil executa)'),
        ),
    ]
