# Generated by Django 6.0.7 on 2026-07-31 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0022_cotabolsapt_atividades_vinculadas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atividadeplanoacao',
            options={'verbose_name': 'Atividade do Plano de Ação', 'verbose_name_plural': 'Matriz de Atividades'},
        ),
        migrations.AlterUniqueTogether(
            name='atividadeplanoacao',
            unique_together={('projeto', 'numero')},
        ),
    ]
