# Generated by Django 6.0.7 on 2026-07-31 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0023_alter_atividadeplanoacao_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planotrabalho',
            name='total_meses',
            field=models.PositiveIntegerField(default=1, verbose_name='Total de Meses do Projeto'),
        ),
    ]
