# Generated by Django 6.0.7 on 2026-07-31 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0024_planotrabalho_total_meses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Macroentrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Número (Ex: 1, 2, 3)')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Macroentrega')),
                ('mes_inicio_relativo', models.PositiveIntegerField(verbose_name='Mês Início')),
                ('mes_fim_relativo', models.PositiveIntegerField(verbose_name='Mês Fim')),
                ('plano_trabalho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='macroentregas', to='cadastros.planotrabalho')),
            ],
            options={
                'verbose_name': 'Macroentrega',
                'verbose_name_plural': 'Macroentregas',
                'ordering': ['numero'],
            },
        ),
    ]
