# Generated by Django 6.0.7 on 2026-08-01 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0025_macroentrega'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistribuicaoContaCota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcela_inicio', models.PositiveIntegerField(verbose_name='Da Parcela')),
                ('parcela_fim', models.PositiveIntegerField(verbose_name='Até a Parcela')),
                ('conta_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.contabancaria', verbose_name='Conta Pagadora')),
                ('cota_pt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribuicoes_contas', to='cadastros.cotabolsapt')),
            ],
            options={
                'verbose_name': 'Distribuição de Pagamento',
                'verbose_name_plural': 'Distribuições de Pagamento',
                'ordering': ['parcela_inicio'],
            },
        ),
    ]
