# Generated by Django 6.0.7 on 2026-08-06 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0026_distribuicaocontacota'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='Número da Parcela')),
                ('termo_bolsa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='cadastros.termobolsa')),
            ],
            options={
                'verbose_name': 'Parcela',
                'verbose_name_plural': 'Parcelas',
                'ordering': ['numero'],
                'unique_together': {('termo_bolsa', 'numero')},
            },
        ),
    ]
