# Generated by Django 6.0.7 on 2026-08-07 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0027_parcela'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolsista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('rg', models.CharField(max_length=30)),
                ('orgao_emissor_rg', models.CharField(max_length=20)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('nacionalidade', models.CharField(default='Brasileiro', max_length=100)),
                ('estado_civil', models.CharField(choices=[('Solteiro', 'Solteiro(a)'), ('Casado', 'Casado(a)'), ('Divorciado', 'Divorciado(a)'), ('Viuvo', 'Viúvo(a)'), ('Outro', 'Outro')], default='Solteiro', max_length=20)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('siape', models.CharField(blank=True, help_text='Apenas para servidores', max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='termobolsa',
            name='carga_horaria_total',
            field=models.PositiveIntegerField(default=0, verbose_name='Carga Horária Total (horas)'),
        ),
        migrations.AddField(
            model_name='termobolsa',
            name='conta_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='termos_pagos', to='cadastros.contabancaria'),
        ),
        migrations.AddField(
            model_name='termobolsa',
            name='modalidade_bolsa',
            field=models.CharField(choices=[('Pesquisa', 'Pesquisa'), ('Ensino', 'Ensino'), ('Extensao', 'Extensão'), ('Desenvolvimento', 'Desenvolvimento Institucional'), ('Inovacao', 'Inovação')], default='Pesquisa', max_length=100),
        ),
        migrations.AddField(
            model_name='termobolsa',
            name='bolsista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='termos', to='cadastros.bolsista'),
        ),
    ]
