# Generated by Django 6.0.7 on 2026-08-07 01:24

from django.db import migrations



def migrar_bolsistas(apps, schema_editor):
    TermoBolsa = apps.get_model('cadastros', 'TermoBolsa')
    Bolsista = apps.get_model('cadastros', 'Bolsista')
    
    for termo in TermoBolsa.objects.all():
        if termo.bolsista_nome and termo.bolsista_cpf:
            # Check if Bolsista exists
            bolsista, created = Bolsista.objects.get_or_create(
                cpf=termo.bolsista_cpf,
                defaults={
                    'nome': termo.bolsista_nome,
                    'rg': '0000000',
                    'orgao_emissor_rg': 'SSP',
                    'nacionalidade': 'Brasileiro',
                    'estado_civil': 'Solteiro',
                }
            )
            termo.bolsista = bolsista
            termo.save()

def reverter_migracao(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0028_bolsista_termobolsa_carga_horaria_total_and_more'),
    ]

    operations = [
        migrations.RunPython(migrar_bolsistas, reverter_migracao),
    ]
