# Generated by Django 6.0.7 on 2026-08-07 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0029_migrate_bolsistas_to_new_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termobolsa',
            name='bolsista_cpf',
        ),
        migrations.RemoveField(
            model_name='termobolsa',
            name='bolsista_nome',
        ),
        migrations.AlterField(
            model_name='termobolsa',
            name='bolsista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='termos', to='cadastros.bolsista'),
        ),
    ]
