# Generated by Django 6.0.7 on 2026-08-07 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0030_remove_termobolsa_bolsista_cpf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termobolsa',
            name='conta_pagamento',
        ),
    ]
