# Generated by Django 6.0.7 on 2026-08-07 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0031_remove_termobolsa_conta_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='termobolsa',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
