# Generated by Django 6.0.7 on 2026-08-16 20:52

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0032_termobolsa_atualizado_em'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FonteDeRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Fonte')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Fonte de Recursos',
                'verbose_name_plural': 'Fontes de Recursos',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterField(
            model_name='contabancaria',
            name='fonte_recurso',
            field=models.ForeignKey(blank=True, help_text='Vincule a uma fonte existente (Ex: EMBRAPII, SEBRAE)', null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.fontederecurso', verbose_name='Fonte do Recurso'),
        ),
        migrations.CreateModel(
            name='HistoricalFonteDeRecurso',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Fonte')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Fonte de Recursos',
                'verbose_name_plural': 'historical Fontes de Recursos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
