# Generated by Django 6.0.7 on 2026-08-16 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0033_fontederecurso_alter_contabancaria_fonte_recurso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetopdi',
            name='vigencia_meses',
            field=models.IntegerField(default=1, verbose_name='Total de Meses Previstos'),
        ),
    ]
