# Generated by Django 6.0.7 on 2026-08-16 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0034_projetopdi_vigencia_meses'),
    ]

    operations = [
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Instituição (Razão Social)')),
                ('natureza_juridica', models.CharField(max_length=255, verbose_name='Natureza Jurídica')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('representante_legal', models.CharField(max_length=255, verbose_name='Representante Legal')),
                ('nacionalidade_representante', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nacionalidade')),
                ('estado_civil_representante', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado Civil')),
                ('cargo_representante', models.CharField(max_length=100, verbose_name='Cargo do Representante')),
                ('ato_nomeacao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ato de Nomeação')),
            ],
            options={
                'verbose_name': 'Pessoa Jurídica',
                'verbose_name_plural': 'Pessoas Jurídicas',
            },
        ),
        migrations.RemoveField(
            model_name='convenio',
            name='instituicao',
        ),
        migrations.RemoveField(
            model_name='projetopdi',
            name='convenio_oficial',
        ),
        migrations.RemoveField(
            model_name='projetopdi',
            name='convenente',
        ),
        migrations.RemoveField(
            model_name='projetopdi',
            name='convenio',
        ),
        migrations.RemoveField(
            model_name='projetopdi',
            name='financiadores',
        ),
        migrations.RemoveField(
            model_name='projetopdi',
            name='interveniente',
        ),
        migrations.AlterField(
            model_name='projetopdi',
            name='termo_de_convenio',
            field=models.FileField(blank=True, null=True, upload_to='convenios/termos/', verbose_name='Termo de Parceria (PDF)'),
        ),
        migrations.CreateModel(
            name='TermoDeParceria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='Número do Termo')),
                ('objeto', models.TextField(blank=True, null=True, verbose_name='Objeto / Descrição')),
                ('data_assinatura', models.DateField(blank=True, null=True, verbose_name='Data de Assinatura')),
                ('ativo', models.BooleanField(default=True)),
                ('concedente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='concedente_em', to='cadastros.pessoajuridica', verbose_name='Concedente')),
                ('convenente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='convenente_em', to='cadastros.pessoajuridica', verbose_name='Convenente')),
                ('interveniente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interveniente_em', to='cadastros.pessoajuridica', verbose_name='Interveniente')),
            ],
            options={
                'verbose_name': 'Termo de Parceria',
                'verbose_name_plural': 'Termos de Parceria',
            },
        ),
        migrations.CreateModel(
            name='PlanoDeTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.IntegerField(default=1, verbose_name='Versão do Plano')),
                ('abordagem_tecnica', models.TextField(blank=True, null=True, verbose_name='Abordagem Técnica')),
                ('abordagem_financeira', models.TextField(blank=True, null=True, verbose_name='Abordagem Financeira')),
                ('produto_entregue', models.TextField(blank=True, null=True, verbose_name='Produto Entregue')),
                ('ativo', models.BooleanField(default=True, verbose_name='Versão Vigente')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('termo_parceria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos_trabalho', to='cadastros.termodeparceria')),
            ],
            options={
                'verbose_name': 'Plano de Trabalho',
                'verbose_name_plural': 'Planos de Trabalho',
                'unique_together': {('termo_parceria', 'versao')},
            },
        ),
        migrations.AddField(
            model_name='projetopdi',
            name='termo_parceria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projetos_pdi', to='cadastros.termodeparceria', verbose_name='Termo de Parceria'),
        ),
        migrations.DeleteModel(
            name='InstituicaoParceira',
        ),
        migrations.DeleteModel(
            name='Convenio',
        ),
    ]
