# Generated by Django 6.0.7 on 2026-08-17 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0035_pessoajuridica_remove_convenio_instituicao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubricaorcamentariapt',
            name='plano_trabalho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubricas', to='cadastros.planodetrabalho'),
        ),
        migrations.AlterField(
            model_name='macroentrega',
            name='plano_trabalho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='macroentregas', to='cadastros.planodetrabalho'),
        ),
        migrations.AddField(
            model_name='planodetrabalho',
            name='aporte_contrapartida',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Contrapartida (R$)'),
        ),
        migrations.AddField(
            model_name='planodetrabalho',
            name='aporte_embrapii',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Aporte EMBRAPII (R$)'),
        ),
        migrations.AddField(
            model_name='planodetrabalho',
            name='aporte_empresa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Aporte Empresa (R$)'),
        ),
        migrations.AddField(
            model_name='planodetrabalho',
            name='aporte_sebrae',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Aporte SEBRAE (R$)'),
        ),
        migrations.AddField(
            model_name='planodetrabalho',
            name='arquivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='projetos/planos_trabalho/', verbose_name='Plano de Trabalho Vigente (PDF)'),
        ),
        migrations.AddField(
            model_name='planodetrabalho',
            name='data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Fim do Plano de Trabalho'),
        ),
        migrations.AddField(
            model_name='planodetrabalho',
            name='data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Início do Plano de Trabalho'),
        ),
        migrations.AddField(
            model_name='planodetrabalho',
            name='total_meses',
            field=models.PositiveIntegerField(default=1, verbose_name='Total de Meses do Projeto'),
        ),
        migrations.AddField(
            model_name='planodetrabalho',
            name='valor_global',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor Global (R$)'),
        ),
        migrations.CreateModel(
            name='CronogramaDesembolso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcela', models.PositiveIntegerField(verbose_name='Nº da Parcela')),
                ('mes_previsto', models.CharField(max_length=50, verbose_name='Mês Previsto (Ex: Mês 1 ou Jan/2026)')),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor da Parcela (R$)')),
                ('plano_trabalho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desembolsos', to='cadastros.planodetrabalho')),
            ],
            options={
                'verbose_name': 'Cronograma de Desembolso',
                'verbose_name_plural': 'Cronogramas de Desembolso',
                'ordering': ['parcela'],
            },
        ),
        migrations.CreateModel(
            name='MembroEquipePT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('funcao', models.CharField(max_length=100, verbose_name='Função no Projeto (Ex: Coordenador, Pesquisador)')),
                ('titulacao', models.CharField(max_length=100, verbose_name='Titulação')),
                ('tipo_recurso', models.CharField(choices=[('DIRETO', 'Recurso Humano Direto'), ('INDIRETO', 'Recurso Humano Indireto')], max_length=50, verbose_name='Tipo de Recurso')),
                ('carga_horaria', models.PositiveIntegerField(default=0, verbose_name='Carga Horária Dedicada (hs)')),
                ('valor_hora', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Hora (R$)')),
                ('plano_trabalho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipe', to='cadastros.planodetrabalho')),
            ],
            options={
                'verbose_name': 'Membro da Equipe do PT',
                'verbose_name_plural': 'Equipe do PT',
            },
        ),
        migrations.DeleteModel(
            name='PlanoTrabalho',
        ),
    ]
