# Generated by Django 6.0.7 on 2026-08-17 01:37

import django.db.models.deletion
from django.db import migrations, models

def populate_subclasses(apps, schema_editor):
    PessoaJuridica = apps.get_model('cadastros', 'PessoaJuridica')
    
    with schema_editor.connection.cursor() as cursor:
        for pj in PessoaJuridica.objects.all():
            print(f"Processando PJ {pj.id}: {pj.nome}")
            if 'FAEPI' in pj.nome or 'Funda' in pj.nome:
                cursor.execute("INSERT INTO cadastros_fundacaoapoio (pessoajuridica_ptr_id) VALUES (%s)", [pj.id])
                print(f"Inserido em FundacaoApoio: {pj.id}")
            elif 'IFAM' in pj.nome or 'Instituto' in pj.nome:
                cursor.execute("INSERT INTO cadastros_ict (pessoajuridica_ptr_id, sigla, nome_nit) VALUES (%s, %s, %s)", [pj.id, 'IFAM', 'Núcleo de Inovação Tecnológica'])
                print(f"Inserido em ICT: {pj.id}")
            else:
                cursor.execute("INSERT INTO cadastros_empresaparceira (pessoajuridica_ptr_id, porte) VALUES (%s, %s)", [pj.id, 'MGE'])
                print(f"Inserido em EmpresaParceira: {pj.id}")

class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0036_alter_rubricaorcamentariapt_plano_trabalho_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgenciaFomento',
            fields=[
                ('pessoajuridica_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cadastros.pessoajuridica')),
                ('esfera', models.CharField(choices=[('FEDERAL', 'Pública Federal'), ('ESTADUAL', 'Pública Estadual'), ('MUNICIPAL', 'Pública Municipal'), ('PRIVADA', 'Entidade Privada')], default='FEDERAL', max_length=20, verbose_name='Esfera')),
                ('sigla', models.CharField(max_length=20, verbose_name='Sigla')),
            ],
            options={
                'verbose_name': 'Agência de Fomento',
                'verbose_name_plural': 'Agências de Fomento',
            },
            bases=('cadastros.pessoajuridica',),
        ),
        migrations.CreateModel(
            name='EmpresaParceira',
            fields=[
                ('pessoajuridica_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cadastros.pessoajuridica')),
                ('porte', models.CharField(choices=[('ME', 'Microempresa'), ('EPP', 'Empresa de Pequeno Porte'), ('MGE', 'Média ou Grande Empresa')], default='MGE', max_length=3, verbose_name='Porte da Empresa')),
                ('segmento_atuacao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Segmento de Atuação')),
            ],
            options={
                'verbose_name': 'Empresa Parceira',
                'verbose_name_plural': 'Empresas Parceiras',
            },
            bases=('cadastros.pessoajuridica',),
        ),
        migrations.CreateModel(
            name='FundacaoApoio',
            fields=[
                ('pessoajuridica_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cadastros.pessoajuridica')),
                ('registro_mec', models.CharField(blank=True, max_length=100, null=True, verbose_name='Registro de Credenciamento MEC/MCTI')),
                ('validade_credenciamento', models.DateField(blank=True, null=True, verbose_name='Validade do Credenciamento')),
            ],
            options={
                'verbose_name': 'Fundação de Apoio',
                'verbose_name_plural': 'Fundações de Apoio',
            },
            bases=('cadastros.pessoajuridica',),
        ),
        migrations.CreateModel(
            name='ICT',
            fields=[
                ('pessoajuridica_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cadastros.pessoajuridica')),
                ('sigla', models.CharField(max_length=20, verbose_name='Sigla da Instituição')),
                ('campus_unidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Campus ou Unidade')),
                ('nome_nit', models.CharField(default='Núcleo de Inovação Tecnológica', max_length=100, verbose_name='Nome do NIT')),
            ],
            options={
                'verbose_name': 'ICT',
                'verbose_name_plural': 'ICTs',
            },
            bases=('cadastros.pessoajuridica',),
        ),
        migrations.RunPython(populate_subclasses),
        migrations.AlterField(
            model_name='termodeparceria',
            name='concedente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='concedente_em', to='cadastros.empresaparceira', verbose_name='Concedente'),
        ),
        migrations.AlterField(
            model_name='termodeparceria',
            name='interveniente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interveniente_em', to='cadastros.fundacaoapoio', verbose_name='Interveniente'),
        ),
        migrations.AlterField(
            model_name='termodeparceria',
            name='convenente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='convenente_em', to='cadastros.ict', verbose_name='Convenente'),
        ),
    ]
