# Generated by Django 6.0.7 on 2026-08-17 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0037_agenciafomento_empresaparceira_fundacaoapoio_ict_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='pessoajuridica_ptr',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cadastros.pessoajuridica'),
        ),
    ]
