# Generated by Django 6.0.7 on 2026-08-17 02:02

from django.db import migrations

def forwards_func(apps, schema_editor):
    Fornecedor = apps.get_model('cadastros', 'Fornecedor')
    PessoaJuridica = apps.get_model('cadastros', 'PessoaJuridica')
    
    for fornecedor in Fornecedor.objects.all():
        # Cria a PessoaJuridica correspondente
        pj = PessoaJuridica.objects.create(
            nome=fornecedor.nome,
            cnpj=fornecedor.cnpj,
            endereco=fornecedor.endereco if fornecedor.endereco else "Não Informado",
            natureza_juridica="Fornecedor",
            representante_legal="Não Informado",
            cargo_representante="Não Informado"
        )
        # Vincula o Fornecedor a essa nova Pessoa Jurídica
        fornecedor.pessoajuridica_ptr = pj
        fornecedor.save()

def backwards_func(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0038_fornecedor_pessoajuridica_ptr'),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func),
    ]
