# Generated by Django 6.0.7 on 2026-08-17 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0039_migrate_fornecedor_data'),
    ]

    operations = [
        migrations.RunSQL("""
            ALTER TABLE almoxarifado_notafiscalalmoxarifado DROP CONSTRAINT IF EXISTS almoxarifado_notafis_fornecedor_id_21ed1831_fk_cadastros;
            ALTER TABLE cadastros_notafiscal DROP CONSTRAINT IF EXISTS cadastros_notafiscal_fornecedor_id_46f7daf6_fk_cadastros;
            ALTER TABLE central_servicos_ordemservico DROP CONSTRAINT IF EXISTS central_servicos_ord_fornecedor_responsav_7c65b00c_fk_cadastros;
            ALTER TABLE manutencao_predial_ordemservico DROP CONSTRAINT IF EXISTS manutencao_predial_o_fornecedor_responsav_cba70ebb_fk_cadastros;
        """),
        migrations.RemoveField(
            model_name='fornecedor',
            name='cnpj',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='nome',
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='pessoajuridica_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cadastros.pessoajuridica'),
        ),
        migrations.RunSQL("""
            ALTER TABLE almoxarifado_notafiscalalmoxarifado ADD CONSTRAINT almoxarifado_notafis_fornecedor_id_21ed1831_fk_cadastros FOREIGN KEY (fornecedor_id) REFERENCES cadastros_fornecedor(pessoajuridica_ptr_id) DEFERRABLE INITIALLY DEFERRED;
            ALTER TABLE cadastros_notafiscal ADD CONSTRAINT cadastros_notafiscal_fornecedor_id_46f7daf6_fk_cadastros FOREIGN KEY (fornecedor_id) REFERENCES cadastros_fornecedor(pessoajuridica_ptr_id) DEFERRABLE INITIALLY DEFERRED;
            ALTER TABLE central_servicos_ordemservico ADD CONSTRAINT central_servicos_ord_fornecedor_responsav_7c65b00c_fk_cadastros FOREIGN KEY (fornecedor_responsavel_id) REFERENCES cadastros_fornecedor(pessoajuridica_ptr_id) DEFERRABLE INITIALLY DEFERRED;
            ALTER TABLE manutencao_predial_ordemservico ADD CONSTRAINT manutencao_predial_o_fornecedor_responsav_cba70ebb_fk_cadastros FOREIGN KEY (fornecedor_responsavel_id) REFERENCES cadastros_fornecedor(pessoajuridica_ptr_id) DEFERRABLE INITIALLY DEFERRED;
        """)
    ]
