# Generated by Django 6.0.7 on 2026-08-17 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0040_remove_fornecedor_cnpj_remove_fornecedor_endereco_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=30, null=True, verbose_name='RG')),
                ('orgao_emissor_rg', models.CharField(blank=True, max_length=20, null=True, verbose_name='Órgão Emissor (RG)')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('nacionalidade', models.CharField(default='Brasileiro', max_length=100, verbose_name='Nacionalidade')),
                ('estado_civil', models.CharField(choices=[('Solteiro', 'Solteiro(a)'), ('Casado', 'Casado(a)'), ('Divorciado', 'Divorciado(a)'), ('Viuvo', 'Viúvo(a)'), ('Outro', 'Outro')], default='Solteiro', max_length=20, verbose_name='Estado Civil')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço Completo')),
                ('cep', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone / Celular')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pessoa Física',
                'verbose_name_plural': 'Pessoas Físicas',
            },
        ),
        migrations.AlterField(
            model_name='termobolsa',
            name='bolsista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='termos', to='cadastros.bolsista'),
        ),
        migrations.CreateModel(
            name='PerfilTerceirizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_contratada', models.CharField(max_length=150, verbose_name='Empresa Contratada')),
                ('funcao', models.CharField(max_length=100, verbose_name='Função / Cargo')),
                ('ativo', models.BooleanField(default=True)),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_terceirizado', to='cadastros.pessoafisica')),
            ],
            options={
                'verbose_name': 'Perfil de Terceirizado',
            },
        ),
        migrations.CreateModel(
            name='PerfilServidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siape', models.CharField(max_length=20, unique=True, verbose_name='Matrícula SIAPE')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo Efetivo')),
                ('lotacao', models.CharField(max_length=100, verbose_name='Unidade / Campus de Lotação')),
                ('interno', models.BooleanField(default=True, verbose_name='Servidor Interno (IFAM)?')),
                ('ativo', models.BooleanField(default=True)),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_servidor', to='cadastros.pessoafisica')),
            ],
            options={
                'verbose_name': 'Perfil de Servidor',
            },
        ),
        migrations.CreateModel(
            name='PerfilColaboradorExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituicao_origem', models.CharField(blank=True, max_length=150, null=True, verbose_name='Instituição/Empresa de Origem')),
                ('expertise', models.CharField(blank=True, max_length=255, null=True, verbose_name='Área de Expertise')),
                ('ativo', models.BooleanField(default=True)),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_colaborador_externo', to='cadastros.pessoafisica')),
            ],
            options={
                'verbose_name': 'Perfil de Colaborador Externo',
            },
        ),
        migrations.CreateModel(
            name='PerfilAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=30, unique=True, verbose_name='Matrícula')),
                ('nivel', models.CharField(choices=[('Tecnico', 'Técnico'), ('Graduacao', 'Graduação'), ('Pos', 'Pós-Graduação'), ('Outro', 'Outro')], default='Graduacao', max_length=30, verbose_name='Nível')),
                ('curso', models.CharField(max_length=150, verbose_name='Curso')),
                ('interno', models.BooleanField(default=True, verbose_name='Aluno Interno (IFAM)?')),
                ('ativo', models.BooleanField(default=True)),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_aluno', to='cadastros.pessoafisica')),
            ],
            options={
                'verbose_name': 'Perfil de Aluno',
            },
        ),
        migrations.CreateModel(
            name='DadoBancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalidade', models.CharField(choices=[('PAGAMENTO_BOLSA', 'Pagamento de Bolsa'), ('HONORARIOS', 'Honorários / Serviços'), ('RESSARCIMENTO', 'Ressarcimento')], default='PAGAMENTO_BOLSA', max_length=50, verbose_name='Finalidade')),
                ('banco_codigo', models.CharField(max_length=10, verbose_name='Código do Banco')),
                ('agencia', models.CharField(max_length=10, verbose_name='Agência')),
                ('conta', models.CharField(max_length=20, verbose_name='Conta Corrente')),
                ('chave_pix', models.CharField(blank=True, max_length=100, null=True, verbose_name='Chave PIX')),
                ('ativo', models.BooleanField(default=True)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dados_bancarios', to='cadastros.pessoafisica')),
            ],
            options={
                'verbose_name': 'Dado Bancário',
                'verbose_name_plural': 'Dados Bancários',
            },
        ),
        migrations.AddField(
            model_name='termobolsa',
            name='pessoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='termos_bolsa', to='cadastros.pessoafisica'),
        ),
    ]
