# Generated by Django 6.0.7 on 2026-08-17 02:53

from django.db import migrations

def migrate_bolsistas(apps, schema_editor):
    Bolsista = apps.get_model('cadastros', 'Bolsista')
    PessoaFisica = apps.get_model('cadastros', 'PessoaFisica')
    PerfilServidor = apps.get_model('cadastros', 'PerfilServidor')
    PerfilAluno = apps.get_model('cadastros', 'PerfilAluno')
    TermoBolsa = apps.get_model('cadastros', 'TermoBolsa')

    for b in Bolsista.objects.all():
        # Cria ou encontra PessoaFisica baseada no CPF
        pf, created = PessoaFisica.objects.get_or_create(
            cpf=b.cpf,
            defaults={
                'nome': b.nome,
                'rg': b.rg,
                'orgao_emissor_rg': b.orgao_emissor_rg,
                'data_nascimento': b.data_nascimento,
                'nacionalidade': b.nacionalidade,
                'estado_civil': b.estado_civil,
                'endereco': b.endereco,
                'cep': b.cep,
                'telefone': b.telefone,
                'email': b.email,
            }
        )

        # Se tinha siape, cria PerfilServidor
        if b.siape:
            PerfilServidor.objects.get_or_create(
                pessoa=pf,
                defaults={
                    'siape': b.siape,
                    'cargo': 'Servidor Legado',
                    'lotacao': 'IFAM',
                    'interno': True,
                    'ativo': True
                }
            )
        else:
            # Caso não tenha siape, assumimos Aluno genérico para não perder a bolsa.
            # O usuário pode refinar depois.
            PerfilAluno.objects.get_or_create(
                pessoa=pf,
                defaults={
                    'matricula': f'LEGADO-{pf.id}',
                    'curso': 'Não Informado',
                    'interno': True,
                    'ativo': True
                }
            )
        
        # Atualiza os Termos de Bolsa vinculados a este Bolsista
        # Como o related_name de bolsista é 'termos' (na migração antiga), iteramos.
        termos = TermoBolsa.objects.filter(bolsista=b)
        for termo in termos:
            termo.pessoa = pf
            termo.save()

def reverse_migrate_bolsistas(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0041_pessoafisica_alter_termobolsa_bolsista_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_bolsistas, reverse_migrate_bolsistas),
    ]
