# Generated by Django 6.0.7 on 2026-08-17 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0042_migrate_bolsistas_to_pessoafisica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termobolsa',
            name='bolsista',
        ),
        migrations.DeleteModel(
            name='Bolsista',
        ),
    ]
