# Generated by Django 6.0.7 on 2026-08-27 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0043_remove_termobolsa_bolsista_delete_bolsista'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicadorResultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='macroentrega',
            name='mes_fim_relativo',
        ),
        migrations.RemoveField(
            model_name='macroentrega',
            name='mes_inicio_relativo',
        ),
        migrations.RemoveField(
            model_name='planodetrabalho',
            name='abordagem_financeira',
        ),
        migrations.RemoveField(
            model_name='planodetrabalho',
            name='abordagem_tecnica',
        ),
        migrations.RemoveField(
            model_name='planodetrabalho',
            name='produto_entregue',
        ),
        migrations.AddField(
            model_name='macroentrega',
            name='data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Data Fim Absoluta'),
        ),
        migrations.AddField(
            model_name='macroentrega',
            name='data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Data Início Absoluta'),
        ),
        migrations.AddField(
            model_name='macroentrega',
            name='micro_entregas',
            field=models.TextField(blank=True, null=True, verbose_name='Micro-Entregas (Rich Text)'),
        ),
        migrations.AddField(
            model_name='planodetrabalho',
            name='caracteristicas_inovadoras',
            field=models.TextField(blank=True, null=True, verbose_name='Características Inovadoras (Rich Text)'),
        ),
        migrations.AddField(
            model_name='planodetrabalho',
            name='desafios_tecnologicos',
            field=models.TextField(blank=True, null=True, verbose_name='Desafios Científicos e Tecnológicos (Rich Text)'),
        ),
        migrations.AddField(
            model_name='planodetrabalho',
            name='escopo_geral',
            field=models.TextField(blank=True, null=True, verbose_name='Escopo Geral (Rich Text)'),
        ),
        migrations.AddField(
            model_name='planodetrabalho',
            name='estrategia',
            field=models.TextField(blank=True, null=True, verbose_name='Estratégia (Rich Text)'),
        ),
        migrations.AddField(
            model_name='planodetrabalho',
            name='estrutura_analitica',
            field=models.TextField(blank=True, null=True, verbose_name='Estrutura Analítica / WBS (Rich Text)'),
        ),
        migrations.AddField(
            model_name='planodetrabalho',
            name='motivacao',
            field=models.TextField(blank=True, null=True, verbose_name='Motivação (Rich Text)'),
        ),
        migrations.AddField(
            model_name='planodetrabalho',
            name='objetivo_geral',
            field=models.TextField(blank=True, null=True, verbose_name='Objetivo Geral'),
        ),
        migrations.AddField(
            model_name='planodetrabalho',
            name='objetivos_especificos',
            field=models.TextField(blank=True, null=True, verbose_name='Objetivos Específicos (Rich Text)'),
        ),
        migrations.AddField(
            model_name='planodetrabalho',
            name='orcamento_descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição do Orçamento (Rich Text)'),
        ),
        migrations.AddField(
            model_name='planodetrabalho',
            name='plano_riscos',
            field=models.TextField(blank=True, null=True, verbose_name='Plano de Riscos (Rich Text)'),
        ),
        migrations.AddField(
            model_name='planodetrabalho',
            name='resultados_esperados',
            field=models.TextField(blank=True, null=True, verbose_name='Resultados Esperados (Rich Text)'),
        ),
        migrations.AddField(
            model_name='planodetrabalho',
            name='solucao_proposta',
            field=models.TextField(blank=True, null=True, verbose_name='Solução Proposta (Rich Text)'),
        ),
        migrations.AddField(
            model_name='planodetrabalho',
            name='tecnologias_utilizadas',
            field=models.TextField(blank=True, null=True, verbose_name='Tecnologias e Ferramentas (Rich Text)'),
        ),
        migrations.AddField(
            model_name='planodetrabalho',
            name='vulnerabilidades',
            field=models.TextField(blank=True, null=True, verbose_name='Vulnerabilidades do Projeto (Rich Text)'),
        ),
        migrations.AddField(
            model_name='projetopdi',
            name='coordenador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_coordenados', to='cadastros.pessoafisica', verbose_name='Coordenador do Projeto'),
        ),
        migrations.AddField(
            model_name='projetopdi',
            name='local_execucao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Local de Execução'),
        ),
        migrations.AddField(
            model_name='planodetrabalho',
            name='indicadores',
            field=models.ManyToManyField(blank=True, related_name='planos_trabalho', to='cadastros.indicadorresultado'),
        ),
    ]
