# Generated by Django 6.0.7 on 2026-08-27 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0044_indicadorresultado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividadeplanoacao',
            name='plano_trabalho',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='cadastros.planodetrabalho'),
        ),
        migrations.AlterUniqueTogether(
            name='atividadeplanoacao',
            unique_together={('plano_trabalho', 'numero')},
        ),
        migrations.AddField(
            model_name='atividadeplanoacao',
            name='data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Data Fim Absoluta'),
        ),
        migrations.AddField(
            model_name='atividadeplanoacao',
            name='data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Data Início Absoluta'),
        ),
        migrations.AlterField(
            model_name='atividadeplanoacao',
            name='descricao',
            field=models.TextField(verbose_name='Descrição da Atividade (Rich Text)'),
        ),
        migrations.AlterField(
            model_name='atividadeplanoacao',
            name='justificativa',
            field=models.TextField(blank=True, null=True, verbose_name='Justificativa (Rich Text)'),
        ),
        migrations.CreateModel(
            name='EntregavelAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Entregável')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregaveis', to='cadastros.atividadeplanoacao')),
            ],
        ),
        migrations.RemoveField(
            model_name='atividadeplanoacao',
            name='entregaveis',
        ),
        migrations.RemoveField(
            model_name='atividadeplanoacao',
            name='mes_fim_relativo',
        ),
        migrations.RemoveField(
            model_name='atividadeplanoacao',
            name='mes_inicio_relativo',
        ),
        migrations.RemoveField(
            model_name='atividadeplanoacao',
            name='projeto',
        ),
    ]
