# Generated by Django 6.0.7 on 2026-08-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0045_alter_atividadeplanoacao_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubricaorcamentariapt',
            name='categoria',
            field=models.CharField(choices=[('PESSOAL', 'Pessoal (RH Direto e Indireto)'), ('CONSUMO', 'Material de Consumo'), ('DIARIAS', 'Diárias, Passagens e Locomoção'), ('TERCEIROS', 'Serviços de Terceiros (PF e PJ)'), ('CAPITAL', 'Capital e Equipamentos'), ('SUPORTE', 'Suporte Operacional / Administrativo'), ('OUTRAS', 'Outras Despesas Correntes')], max_length=50, verbose_name='Categoria / Dispêndio'),
        ),
    ]
