# Generated by Django 6.0.7 on 2026-08-28 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0046_alter_rubricaorcamentariapt_categoria'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='planodetrabalho',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='projetopdi',
            name='termo_parceria',
        ),
        migrations.AddField(
            model_name='planodetrabalho',
            name='congelado',
            field=models.BooleanField(default=False, verbose_name='Plano Congelado (Bloqueio de Edição)'),
        ),
        migrations.AddField(
            model_name='planodetrabalho',
            name='projeto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planos_trabalho', to='cadastros.projetopdi'),
        ),
        migrations.AddField(
            model_name='planodetrabalho',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho / Em Edição'), ('CONGELADO_VIGENTE', 'Congelado Vigente (Em Execução)'), ('HISTORICO', 'Histórico (Substituído)')], default='RASCUNHO', max_length=20, verbose_name='Status do Plano'),
        ),
        migrations.AddField(
            model_name='planodetrabalho',
            name='termo_homologador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos_homologados', to='cadastros.termodeparceria', verbose_name='Termo Homologador'),
        ),
        migrations.AddField(
            model_name='projetopdi',
            name='fase',
            field=models.CharField(choices=[('PROSPECCAO', 'Prospecção'), ('EXECUCAO', 'Execução'), ('PRESTACAO_CONTAS', 'Prestação de Contas'), ('ENCERRADO', 'Encerrado'), ('CANCELADO', 'Cancelado')], default='PROSPECCAO', max_length=20, verbose_name='Fase do Projeto'),
        ),
        migrations.AddField(
            model_name='termodeparceria',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='termos_parceria', to='cadastros.projetopdi', verbose_name='Projeto Mestre'),
        ),
        migrations.RemoveField(
            model_name='planodetrabalho',
            name='termo_parceria',
        ),

        migrations.AlterUniqueTogether(
            name='planodetrabalho',
            unique_together={('projeto', 'versao')},
        ),
    ]
