# Generated by Django 6.0.7 on 2026-08-29 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0047_alter_planodetrabalho_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetopdi',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_em_prospeccao', to='cadastros.empresaparceira', verbose_name='Empresa Parceira (Prospecção)'),
        ),
    ]
