# Generated by Django 6.0.7 on 2026-08-29 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0048_projetopdi_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projetopdi',
            name='empresa',
        ),
        migrations.AddField(
            model_name='projetopdi',
            name='concedente',
            field=models.ForeignKey(blank=True, help_text='Quem está financiando a demanda principal (ex: Empresa ou EMBRAPII no caso de PDC).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_concedidos', to='cadastros.pessoajuridica', verbose_name='Concedente (Empresa/Agência)'),
        ),
        migrations.AddField(
            model_name='projetopdi',
            name='convenente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_conveniados', to='cadastros.ict', verbose_name='Convenente (ICT Executora)'),
        ),
        migrations.AddField(
            model_name='projetopdi',
            name='interveniente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_intervenientes', to='cadastros.fundacaoapoio', verbose_name='Interveniente (Fundação de Apoio)'),
        ),
        migrations.AlterField(
            model_name='termodeparceria',
            name='concedente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termos_concedidos', to='cadastros.pessoajuridica', verbose_name='Concedente (Empresa/Agência)'),
        ),
    ]
