# Generated by Django 6.0.7 on 2026-08-29 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0049_remove_projetopdi_empresa_projetopdi_concedente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermoCooperacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='Número do Termo (Ex: TC Nº 17/2020)')),
                ('objeto', models.TextField(verbose_name='Objeto do Acordo Mestre')),
                ('valor_global', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Global (R$)')),
                ('vigencia_inicio', models.DateField(verbose_name='Início da Vigência')),
                ('vigencia_fim', models.DateField(verbose_name='Fim da Vigência')),
                ('ativo', models.BooleanField(default=True)),
                ('concedente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termos_cooperacao_concedidos', to='cadastros.pessoajuridica', verbose_name='Concedente Mestre')),
                ('convenente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termos_cooperacao_conveniados', to='cadastros.ict', verbose_name='Convenente Mestre')),
            ],
            options={
                'verbose_name': 'Termo de Cooperação / Credenciamento',
                'verbose_name_plural': 'Termos de Cooperação / Credenciamentos',
                'ordering': ['-vigencia_inicio'],
            },
        ),
        migrations.AddField(
            model_name='projetopdi',
            name='termo_cooperacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_vinculados', to='cadastros.termocooperacao', verbose_name='Termo de Cooperação (Guarda-Chuva)'),
        ),
    ]
