# Generated by Django 6.0.7 on 2026-08-31 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0050_termocooperacao_projetopdi_termo_cooperacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projetopdi',
            name='termo_cooperacao',
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Programa (Ex: PDC 2025)')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição do Programa')),
                ('ativo', models.BooleanField(default=True)),
                ('termo_cooperacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programas', to='cadastros.termocooperacao', verbose_name='Termo de Cooperação (Guarda-Chuva)')),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programas',
            },
        ),
        migrations.AddField(
            model_name='projetopdi',
            name='programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_vinculados', to='cadastros.programa', verbose_name='Programa (Acordo Mestre / Guarda-Chuva)'),
        ),
    ]
