# Generated by Django 6.0.7 on 2026-08-31 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0051_remove_projetopdi_termo_cooperacao_programa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='termocooperacao',
            name='arquivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='termos_cooperacao/', verbose_name='Cópia do Documento (PDF)'),
        ),
        migrations.AlterField(
            model_name='termocooperacao',
            name='concedente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termos_cooperacao_concedidos', to='cadastros.pessoajuridica', verbose_name='Concedente'),
        ),
        migrations.AlterField(
            model_name='termocooperacao',
            name='convenente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termos_cooperacao_conveniados', to='cadastros.ict', verbose_name='Convenente'),
        ),
        migrations.AlterField(
            model_name='termocooperacao',
            name='numero',
            field=models.CharField(max_length=50, unique=True, verbose_name='Número do Termo'),
        ),
        migrations.AlterField(
            model_name='termocooperacao',
            name='objeto',
            field=models.TextField(verbose_name='Objeto'),
        ),
        migrations.CreateModel(
            name='AditivoTermoCooperacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, verbose_name='Número do Aditivo')),
                ('descricao', models.TextField(verbose_name='Objeto da Alteração')),
                ('nova_data_fim', models.DateField(blank=True, null=True, verbose_name='Nova Data de Fim (se houver prorrogação)')),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='termos_cooperacao/aditivos/', verbose_name='Cópia do Aditivo (PDF)')),
                ('data_assinatura', models.DateField(blank=True, null=True, verbose_name='Data de Assinatura')),
                ('termo_cooperacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aditivos', to='cadastros.termocooperacao', verbose_name='Termo de Cooperação')),
            ],
            options={
                'verbose_name': 'Aditivo de Termo de Cooperação',
                'verbose_name_plural': 'Aditivos de Termo de Cooperação',
                'ordering': ['-data_assinatura'],
            },
        ),
    ]
