# Generated by Django 6.0.7 on 2026-08-31 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0052_termocooperacao_arquivo_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termocooperacao',
            name='concedente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termos_cooperacao_concedidos', to='cadastros.pessoajuridica', verbose_name='Parceiro'),
        ),
        migrations.AlterField(
            model_name='termocooperacao',
            name='convenente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termos_cooperacao_conveniados', to='cadastros.ict', verbose_name='ICT'),
        ),
    ]
