# Generated by Django 6.0.7 on 2026-08-31 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0053_alter_termocooperacao_concedente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ict',
            name='is_executora',
            field=models.BooleanField(default=False, help_text="Marque se esta for a instituição matriz do sistema (ex: IFAM). Ela não aparecerá como 'Parceiro' em novos acordos.", verbose_name='É a ICT Executora (Sede/Polo)?'),
        ),
    ]
