# Generated by Django 6.0.7 on 2026-08-31 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0054_ict_is_executora'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresaparceira',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Fantasia'),
        ),
        migrations.AddField(
            model_name='fundacaoapoio',
            name='sigla',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Sigla da Fundação'),
        ),
    ]
