# Generated by Django 6.0.7 on 2026-08-31 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0055_empresaparceira_nome_fantasia_fundacaoapoio_sigla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresaparceira',
            name='nome_fantasia',
            field=models.CharField(default='', max_length=255, verbose_name='Nome Fantasia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='sigla',
            field=models.CharField(default='', max_length=50, verbose_name='Sigla / Nome Curto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fundacaoapoio',
            name='sigla',
            field=models.CharField(default='', max_length=20, verbose_name='Sigla da Fundação'),
            preserve_default=False,
        ),
    ]
