# Generated by Django 6.0.7 on 2026-09-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0056_alter_empresaparceira_nome_fantasia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetopdi',
            name='vigencia_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Fim da Vigência Geral'),
        ),
        migrations.AlterField(
            model_name='projetopdi',
            name='vigencia_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Início da Vigência Geral'),
        ),
    ]
