# Generated by Django 6.0.7 on 2026-09-01 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0057_vigencia_nullable_para_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividadeplanoacao',
            name='data_fim',
        ),
        migrations.RemoveField(
            model_name='atividadeplanoacao',
            name='data_inicio',
        ),
        migrations.AddField(
            model_name='atividadeplanoacao',
            name='mes_fim',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Mês de Fim (Ex: 9)'),
        ),
        migrations.AddField(
            model_name='atividadeplanoacao',
            name='mes_inicio',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Mês de Início (Ex: 1)'),
        ),
    ]
