# Generated by Django 6.0.7 on 2026-09-02 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0058_remove_atividadeplanoacao_data_fim_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='atividadeplanoacao',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='atividadeplanoacao',
            name='numero',
            field=models.IntegerField(default=1, verbose_name='Número'),
        ),
    ]
