# Generated by Django 6.0.7 on 2026-09-04 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0059_alter_atividadeplanoacao_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoafisica',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Vínculo institucional exclusivo do Administrador do Sistema.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pessoa_fisica', to=settings.AUTH_USER_MODEL, verbose_name='Conta de Acesso (User)'),
        ),
    ]
