# Generated by Django 6.0.7 on 2026-09-04 16:19

from django.db import migrations
import re


def link_existing_users_to_pessoafisica(apps, schema_editor):
    """
    Migração de dados para vincular automaticamente instâncias existentes de User e PessoaFisica.
    Estratégia de pareamento:
    1. Primeiro tenta casar por CPF (remove pontuações)
    2. Para usuários restantes, tenta casar por email
    3. Trata exceções com segurança para não abortar a migração
    """
    User = apps.get_model('auth', 'User')
    PessoaFisica = apps.get_model('cadastros', 'PessoaFisica')
    
    # Tenta carregar o modelo PerfilUsuario do almoxarifado (legado)
    try:
        PerfilUsuario = apps.get_model('almoxarifado', 'PerfilUsuario')
        use_legacy_profile = True
    except LookupError:
        # Se o app almoxarifado não existir ou não tiver PerfilUsuario, ignora a legada
        use_legacy_profile = False
    
    # Função auxiliar para limpar CPF (remover pontuações)
    def clean_cpf(cpf):
        if not cpf:
            return None
        return re.sub(r'[^\d]', '', str(cpf))
    
    linked_count = 0
    skipped_count = 0
    
    # Estratégia 1: Pareamento por CPF (usando perfil legado se disponível)
    if use_legacy_profile:
        for user in User.objects.all():
            if hasattr(user, 'perfil') and user.perfil:
                cpf_legado = clean_cpf(getattr(user.perfil, 'cpf', None))
                if cpf_legado:
                    try:
                        # Busca PessoaFisica pelo CPF limpo
                        pessoa_fisica = PessoaFisica.objects.filter(cpf__icontains=cpf_legado).first()
                        if pessoa_fisica and not pessoa_fisica.user:
                            pessoa_fisica.user = user
                            pessoa_fisica.save(update_fields=['user'])
                            linked_count += 1
                    except Exception as e:
                        # Registra erro mas não aborta a migração
                        print(f"Erro ao vincular usuário {user.username} por CPF: {e}")
                        skipped_count += 1
    
    # Estratégia 2: Pareamento por email (para usuários ainda não vinculados)
    for user in User.objects.all():
        if not hasattr(user, 'pessoa_fisica') or not user.pessoa_fisica:
            if user.email:
                try:
                    # Busca PessoaFisica pelo email exato
                    pessoa_fisica = PessoaFisica.objects.filter(email__iexact=user.email).first()
                    if pessoa_fisica and not pessoa_fisica.user:
                        pessoa_fisica.user = user
                        pessoa_fisica.save(update_fields=['user'])
                        linked_count += 1
                except Exception as e:
                    # Registra erro mas não aborta a migração
                    print(f"Erro ao vincular usuário {user.username} por email: {e}")
                    skipped_count += 1
    
    print(f"Vinculação concluída: {linked_count} usuários vinculados, {skipped_count} erros/skips")


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0060_add_user_to_pessoafisica'),
    ]

    operations = [
        migrations.RunPython(link_existing_users_to_pessoafisica, migrations.RunPython.noop),
    ]
