# Generated by Django 6.0.7 on 2026-09-04 16:57

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0061_link_existing_users_to_pessoafisica'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcela',
            name='comprovante_pagamento',
            field=models.FileField(blank=True, null=True, upload_to='comprovantes_pagamento_bolsas/', verbose_name='Comprovante de Pagamento (PDF)'),
        ),
        migrations.AddField(
            model_name='parcela',
            name='conta_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcelas_pagas', to='cadastros.contabancaria', verbose_name='Conta Bancária Pagadora'),
        ),
        migrations.AddField(
            model_name='parcela',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data Efetiva de Pagamento'),
        ),
        migrations.AddField(
            model_name='parcela',
            name='mes_competencia',
            field=models.DateField(blank=True, null=True, verbose_name='Mês de Competência'),
        ),
        migrations.AddField(
            model_name='parcela',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Aguardando Envio do RA'), ('EM_ANALISE', 'RA Submetido / Em Análise'), ('APROVADO', 'Atestado pelo Coordenador (Apto para Pagamento)'), ('PAGO', 'Pago / Liquidado'), ('CANCELADO', 'Cancelado / Não Executado')], default='PENDENTE', max_length=25, verbose_name='Status da Parcela'),
        ),
        migrations.AddField(
            model_name='parcela',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor Nominal da Parcela (R$)'),
        ),
    ]
