# Generated by Django 6.0.7 on 2026-09-04 16:57

from django.db import migrations
from dateutil.relativedelta import relativedelta


def populate_existing_parcelas_financial_data(apps, schema_editor):
    """
    Migração de dados para preencher campos financeiros de parcelas existentes.
    Estratégia:
    1. Preencher valor das parcelas com valor_parcela do termo
    2. Calcular mes_competencia baseado em vigencia_inicio do termo
    """
    Parcela = apps.get_model('cadastros', 'Parcela')
    TermoBolsa = apps.get_model('cadastros', 'TermoBolsa')
    
    updated_count = 0
    skipped_count = 0
    
    for parcela in Parcela.objects.all():
        try:
            termo = parcela.termo_bolsa
            
            # Preencher valor se estiver zerado ou nulo
            if not parcela.valor or parcela.valor == 0:
                if termo.valor_parcela:
                    parcela.valor = termo.valor_parcela
                    updated_count += 1
            
            # Calcular mes_competencia se estiver nulo e termo tiver vigencia_inicio
            if not parcela.mes_competencia and termo.vigencia_inicio:
                # Calcular competência: vigencia_inicio + (numero-1) meses
                data_comp = termo.vigencia_inicio + relativedelta(months=parcela.numero - 1)
                parcela.mes_competencia = data_comp
                updated_count += 1
            
            # Definir status padrão se estiver vazio
            if not parcela.status:
                parcela.status = 'PENDENTE'
                updated_count += 1
            
            parcela.save(update_fields=['valor', 'mes_competencia', 'status'])
            
        except Exception as e:
            # Registra erro mas não aborta a migração
            print(f"Erro ao atualizar parcela {parcela.id}: {e}")
            skipped_count += 1
    
    print(f"Atualização concluída: {updated_count} campos atualizados, {skipped_count} erros/skips")


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0062_add_financial_fields_to_parcela'),
    ]

    operations = [
        migrations.RunPython(populate_existing_parcelas_financial_data, migrations.RunPython.noop),
    ]
