# Generated by Django 6.0.7 on 2026-09-06 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0063_populate_existing_parcelas_financial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='macroentrega',
            name='trl',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(3, 'TRL 3 — Prova de Conceito Analítica/Experimental'), (4, 'TRL 4 — Validação de Componentes em Laboratório'), (5, 'TRL 5 — Validação em Ambiente Relevante/Simulado'), (6, 'TRL 6 — Demonstração de Protótipo Operacional')], help_text='Nível de maturidade tecnológica no padrão EMBRAPII (escala 3 a 6).', null=True, verbose_name='Nível TRL (Maturidade Tecnológica)'),
        ),
    ]
