# Generated by Django 6.0.7 on 2026-09-06 23:04

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0064_macroentrega_trl'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCotaBolsaPT',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('perfil_funcao', models.CharField(max_length=150, verbose_name='Perfil/Função (Ex: Pesquisador Sênior)')),
                ('quantidade_vagas', models.PositiveIntegerField(default=1, verbose_name='Quantidade de Vagas')),
                ('parcelas_previstas', models.PositiveIntegerField(verbose_name='Total de Parcelas Previstas')),
                ('valor_global_previsto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Global Previsto (R$)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('projeto', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cadastros.projetopdi')),
            ],
            options={
                'verbose_name': 'historical cota bolsa pt',
                'verbose_name_plural': 'historical cota bolsa pts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPlanoDeTrabalho',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho / Em Edição'), ('CONGELADO_VIGENTE', 'Congelado Vigente (Em Execução)'), ('HISTORICO', 'Histórico (Substituído)')], default='RASCUNHO', max_length=20, verbose_name='Status do Plano')),
                ('congelado', models.BooleanField(default=False, verbose_name='Plano Congelado (Bloqueio de Edição)')),
                ('versao', models.IntegerField(default=1, verbose_name='Versão do Plano')),
                ('arquivo_pdf', models.TextField(blank=True, max_length=100, null=True, verbose_name='Plano de Trabalho Vigente (PDF)')),
                ('motivacao', models.TextField(blank=True, null=True, verbose_name='Motivação (Rich Text)')),
                ('objetivo_geral', models.TextField(blank=True, null=True, verbose_name='Objetivo Geral')),
                ('objetivos_especificos', models.TextField(blank=True, null=True, verbose_name='Objetivos Específicos (Rich Text)')),
                ('escopo_geral', models.TextField(blank=True, null=True, verbose_name='Escopo Geral (Rich Text)')),
                ('estrutura_analitica', models.TextField(blank=True, null=True, verbose_name='Estrutura Analítica / WBS (Rich Text)')),
                ('tecnologias_utilizadas', models.TextField(blank=True, null=True, verbose_name='Tecnologias e Ferramentas (Rich Text)')),
                ('vulnerabilidades', models.TextField(blank=True, null=True, verbose_name='Vulnerabilidades do Projeto (Rich Text)')),
                ('plano_riscos', models.TextField(blank=True, null=True, verbose_name='Plano de Riscos (Rich Text)')),
                ('estrategia', models.TextField(blank=True, null=True, verbose_name='Estratégia (Rich Text)')),
                ('caracteristicas_inovadoras', models.TextField(blank=True, null=True, verbose_name='Características Inovadoras (Rich Text)')),
                ('resultados_esperados', models.TextField(blank=True, null=True, verbose_name='Resultados Esperados (Rich Text)')),
                ('desafios_tecnologicos', models.TextField(blank=True, null=True, verbose_name='Desafios Científicos e Tecnológicos (Rich Text)')),
                ('solucao_proposta', models.TextField(blank=True, null=True, verbose_name='Solução Proposta (Rich Text)')),
                ('orcamento_descricao', models.TextField(blank=True, null=True, verbose_name='Descrição do Orçamento (Rich Text)')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Início do Plano de Trabalho')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Fim do Plano de Trabalho')),
                ('total_meses', models.PositiveIntegerField(default=1, verbose_name='Total de Meses do Projeto')),
                ('valor_global', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor Global (R$)')),
                ('aporte_empresa', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Aporte Empresa (R$)')),
                ('aporte_embrapii', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Aporte EMBRAPII (R$)')),
                ('aporte_sebrae', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Aporte SEBRAE (R$)')),
                ('aporte_contrapartida', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Contrapartida (R$)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Versão Vigente')),
                ('data_criacao', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('projeto', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cadastros.projetopdi')),
                ('termo_homologador', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cadastros.termodeparceria', verbose_name='Termo Homologador')),
            ],
            options={
                'verbose_name': 'historical Plano de Trabalho',
                'verbose_name_plural': 'historical Planos de Trabalho',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRubricaOrcamentariaPT',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('PESSOAL', 'Pessoal (RH Direto e Indireto)'), ('CONSUMO', 'Material de Consumo'), ('DIARIAS', 'Diárias, Passagens e Locomoção'), ('TERCEIROS', 'Serviços de Terceiros (PF e PJ)'), ('CAPITAL', 'Capital e Equipamentos'), ('SUPORTE', 'Suporte Operacional / Administrativo'), ('OUTRAS', 'Outras Despesas Correntes')], max_length=50, verbose_name='Categoria / Dispêndio')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição do Item')),
                ('valor_previsto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Previsto (R$)')),
                ('fonte_recurso', models.CharField(choices=[('EMPRESA', 'Empresa'), ('EMBRAPII', 'EMBRAPII'), ('SEBRAE', 'SEBRAE'), ('CONTRAPARTIDA', 'Contrapartida ICT')], max_length=50, verbose_name='Fonte do Recurso')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plano_trabalho', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cadastros.planodetrabalho')),
            ],
            options={
                'verbose_name': 'historical Rubrica Orçamentária',
                'verbose_name_plural': 'historical Rubricas Orçamentárias',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
