# Generated by Django 6.0.7 on 2026-09-07 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0065_add_history_plano_cota_rubrica'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='conta_bancaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos', to='cadastros.contabancaria', verbose_name='Conta Bancária Pagadora'),
        ),
    ]
