# Generated by Django 6.0.7 on 2026-09-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0066_processo_conta_bancaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilservidor',
            name='cargo_direcao',
            field=models.CharField(choices=[('NENHUM', 'Nenhum / Sem Cargo Comissionado'), ('CD1', 'CD-01 (Reitor / Pró-Reitor / Diretor-Geral)'), ('CD2', 'CD-02 (Diretor Sistêmico / Diretor de Campus Avançado)'), ('CD3', 'CD-03 (Diretor de Departamento / Coordenador-Geral)'), ('CD4', 'CD-04 (Coordenador de Curso / Chefe de Setor)'), ('FG', 'Função Gratificada (FG / FUC)')], default='NENHUM', max_length=10, verbose_name='Cargo de Direção / Função Gratificada'),
        ),
        migrations.AddField(
            model_name='termobolsa',
            name='autorizacao_excepcional',
            field=models.BooleanField(default=False, verbose_name='Autorização Excepcional Deferida?'),
        ),
        migrations.AddField(
            model_name='termobolsa',
            name='carga_horaria_semanal',
            field=models.PositiveIntegerField(default=20, verbose_name='Carga Horária Semanal (horas/semana)'),
        ),
        migrations.AddField(
            model_name='termobolsa',
            name='justificativa_excepcional',
            field=models.TextField(blank=True, null=True, verbose_name='Justificativa / Parecer da Autorização Excepcional'),
        ),
    ]
