# Generated by Django 6.0.7 on 2026-09-07 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0067_perfilservidor_cargo_direcao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoTransicaoFase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase_anterior', models.CharField(choices=[('PROSPECCAO', 'Prospecção'), ('EXECUCAO', 'Execução'), ('PRESTACAO_CONTAS', 'Prestação de Contas'), ('ENCERRADO', 'Encerrado'), ('CANCELADO', 'Cancelado')], max_length=20)),
                ('fase_nova', models.CharField(choices=[('PROSPECCAO', 'Prospecção'), ('EXECUCAO', 'Execução'), ('PRESTACAO_CONTAS', 'Prestação de Contas'), ('ENCERRADO', 'Encerrado'), ('CANCELADO', 'Cancelado')], max_length=20)),
                ('data_transicao', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora da Transição')),
                ('justificativa', models.TextField(blank=True, null=True, verbose_name='Justificativa / Parecer')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_fases', to='cadastros.projetopdi')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Responsável pela Transição')),
            ],
            options={
                'verbose_name': 'Histórico de Transição de Fase',
                'verbose_name_plural': 'Histórico de Transições de Fases',
                'ordering': ['-data_transicao'],
            },
        ),
    ]
