# Generated by Django 6.0.7 on 2026-09-07 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0068_historicotransicaofase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicotransicaofase',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico_fases', to='cadastros.projetopdi'),
        ),
    ]
