# Generated by Django 6.0.7 on 2026-09-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0069_alter_historicotransicaofase_projeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='termodeparceria',
            name='ano',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ano de Emissão'),
        ),
        migrations.AddField(
            model_name='termodeparceria',
            name='sequencial',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número Sequencial'),
        ),
        migrations.AddField(
            model_name='termodeparceria',
            name='tipo_instrumento',
            field=models.CharField(choices=[('CONVENIO', 'Convênio de P&D&I (Legado)'), ('ACORDO_PARCERIA', 'Acordo de Parceria para P&D&I (Marco Legal CT&I)'), ('TERMO_COOPERACAO', 'Termo de Cooperação / Acordo Guarda-Chuva'), ('NDA', 'Acordo de Confidencialidade e Sigilo'), ('STE', 'Prestação de Serviços Técnicos Especializados'), ('LICENCIAMENTO', 'Contrato de Licenciamento / Transferência de Tecnologia'), ('COMPARTILHAMENTO', 'Termo de Compartilhamento de Infraestrutura/Laboratório')], default='CONVENIO', max_length=30, verbose_name='Tipo de Instrumento'),
        ),
        migrations.AlterField(
            model_name='termodeparceria',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='termodeparceria',
            name='numero',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Número do Instrumento'),
        ),
    ]
