# Generated by Django 6.0.7 on 2026-09-08 20:07

import re
from django.db import migrations, models


def classificar_e_extrair_numeracao(apps, schema_editor):
    TermoDeParceria = apps.get_model('cadastros', 'TermoDeParceria')
    for termo in TermoDeParceria.objects.all():
        if termo.numero:
            match = re.search(r'(\d+)/(\d{4})', termo.numero)
            if match:
                termo.sequencial = int(match.group(1))
                termo.ano = int(match.group(2))

        if termo.numero and re.match(r'^\s*AP\b', termo.numero.upper()):
            termo.tipo_instrumento = 'ACORDO_PARCERIA'
        else:
            termo.tipo_instrumento = 'CONVENIO'

        termo.save(update_fields=['tipo_instrumento', 'sequencial', 'ano'])


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0070_termodeparceria_ano_termodeparceria_sequencial_and_more'),
    ]

    operations = [
        migrations.RunPython(classificar_e_extrair_numeracao, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='termodeparceria',
            constraint=models.UniqueConstraint(
                condition=models.Q(('ano__isnull', False), ('sequencial__isnull', False)),
                fields=('tipo_instrumento', 'sequencial', 'ano'),
                name='unique_sequencial_ano_por_tipo'
            ),
        ),
    ]
