# Generated by Django 6.0.7 on 2026-09-11 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0071_auto_20260908_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='termo_cooperacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programas', to='cadastros.termocooperacao', verbose_name='Termo de Cooperação'),
        ),
        migrations.AlterField(
            model_name='projetopdi',
            name='programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_vinculados', to='cadastros.programa', verbose_name='Programa de Fomento'),
        ),
        migrations.AlterField(
            model_name='termodeparceria',
            name='tipo_instrumento',
            field=models.CharField(choices=[('CONVENIO', 'Convênio de P&D&I (Legado)'), ('ACORDO_PARCERIA', 'Acordo de Parceria para P&D&I (Marco Legal CT&I)'), ('TERMO_COOPERACAO', 'Termo de Cooperação'), ('NDA', 'Acordo de Confidencialidade e Sigilo'), ('STE', 'Prestação de Serviços Técnicos Especializados'), ('LICENCIAMENTO', 'Contrato de Licenciamento / Transferência de Tecnologia'), ('COMPARTILHAMENTO', 'Termo de Compartilhamento de Infraestrutura/Laboratório')], default='ACORDO_PARCERIA', max_length=30, verbose_name='Tipo de Instrumento'),
        ),
    ]
