# Generated by Django 6.0.7 on 2026-09-11 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0072_alter_programa_termo_cooperacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetopdi',
            name='programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_vinculados', to='cadastros.programa', verbose_name='Programa Associado'),
        ),
    ]
