# Generated by Django 6.0.7 on 2026-09-11 00:37

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0073_alter_projetopdi_programa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoInstrumentoJuridico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='Nome do Tipo de Instrumento')),
                ('sigla', models.CharField(max_length=20, unique=True, verbose_name='Sigla / Prefixo')),
                ('fundamentacao_legal', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fundamentação Legal')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('exige_fundacao_apoio', models.BooleanField(default=False, verbose_name='Exige Fundação de Apoio (Interveniente-Anuente)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Tipo de Instrumento Jurídico',
                'verbose_name_plural': 'Tipos de Instrumentos Jurídicos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalTipoInstrumentoJuridico',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=150, verbose_name='Nome do Tipo de Instrumento')),
                ('sigla', models.CharField(db_index=True, max_length=20, verbose_name='Sigla / Prefixo')),
                ('fundamentacao_legal', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fundamentação Legal')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('exige_fundacao_apoio', models.BooleanField(default=False, verbose_name='Exige Fundação de Apoio (Interveniente-Anuente)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Tipo de Instrumento Jurídico',
                'verbose_name_plural': 'historical Tipos de Instrumentos Jurídicos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='termocooperacao',
            name='tipo_instrumento_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='termos_cooperacao', to='cadastros.tipoinstrumentojuridico', verbose_name='Tipo de Instrumento'),
        ),
        migrations.AddField(
            model_name='termodeparceria',
            name='tipo_instrumento_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='cadastros.tipoinstrumentojuridico', verbose_name='Tipo de Instrumento (Parametrizado)'),
        ),
    ]
