# Generated by Django 6.0.7 on 2026-09-11 01:06

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0075_seed_tipos_instrumentos_juridicos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='termoaditivo',
            options={'ordering': ['-data_assinatura'], 'verbose_name': 'Termo Aditivo', 'verbose_name_plural': 'Termos Aditivos'},
        ),
        migrations.AddField(
            model_name='aditivotermocooperacao',
            name='numero_processo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Processo SIPAC/SEI'),
        ),
        migrations.AddField(
            model_name='aditivotermocooperacao',
            name='tipo_aditivo',
            field=models.CharField(choices=[('PRORROGACAO', 'Prorrogação de Vigência (Prazo)'), ('VALOR', 'Acréscimo / Supressão de Recursos (Valor)'), ('ESCOPO', 'Alteração de Escopo / Plano de Trabalho'), ('MISTO', 'Misto (Prazo, Valor e Escopo)'), ('OUTRO', 'Outros Ajustes Formais')], default='PRORROGACAO', max_length=30, verbose_name='Tipo de Aditamento'),
        ),
        migrations.AddField(
            model_name='aditivotermocooperacao',
            name='valor_aditivo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Aditivado (R$)'),
        ),
        migrations.AddField(
            model_name='termoaditivo',
            name='numero_processo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Processo Administrativo (SIPAC/SEI)'),
        ),
        migrations.AddField(
            model_name='termoaditivo',
            name='termo_parceria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aditivos', to='cadastros.termodeparceria', verbose_name='Termo de Parceria'),
        ),
        migrations.AddField(
            model_name='termoaditivo',
            name='tipo_aditivo',
            field=models.CharField(choices=[('PRORROGACAO', 'Prorrogação de Vigência (Prazo)'), ('VALOR', 'Acréscimo / Supressão de Recursos (Valor)'), ('ESCOPO', 'Alteração de Escopo / Plano de Trabalho'), ('MISTO', 'Misto (Prazo, Valor e Escopo)'), ('OUTRO', 'Outros Ajustes Formais')], default='PRORROGACAO', max_length=30, verbose_name='Tipo de Aditamento'),
        ),
        migrations.AddField(
            model_name='termoaditivo',
            name='valor_aditivo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Aditivado (R$)'),
        ),
        migrations.AlterField(
            model_name='aditivotermocooperacao',
            name='arquivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='instrumentos/aditivos/', verbose_name='Cópia do Aditivo Assinado (PDF)'),
        ),
        migrations.AlterField(
            model_name='aditivotermocooperacao',
            name='descricao',
            field=models.TextField(verbose_name='Objeto / Justificativa da Alteração'),
        ),
        migrations.AlterField(
            model_name='aditivotermocooperacao',
            name='numero',
            field=models.CharField(max_length=50, verbose_name='Número do Aditivo'),
        ),
        migrations.AlterField(
            model_name='termoaditivo',
            name='arquivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='instrumentos/aditivos/', verbose_name='Cópia do Aditivo Assinado (PDF)'),
        ),
        migrations.AlterField(
            model_name='termoaditivo',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Objeto / Justificativa da Alteração'),
        ),
        migrations.AlterField(
            model_name='termoaditivo',
            name='nova_data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Nova Data de Término (Se houver prorrogação)'),
        ),
        migrations.AlterField(
            model_name='termoaditivo',
            name='numero',
            field=models.CharField(max_length=50, verbose_name='Número do Aditivo'),
        ),
        migrations.AlterField(
            model_name='termoaditivo',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aditivos', to='cadastros.projetopdi', verbose_name='Projeto PDI Vinculado'),
        ),
        migrations.CreateModel(
            name='HistoricalAditivoTermoCooperacao',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, verbose_name='Número do Aditivo')),
                ('tipo_aditivo', models.CharField(choices=[('PRORROGACAO', 'Prorrogação de Vigência (Prazo)'), ('VALOR', 'Acréscimo / Supressão de Recursos (Valor)'), ('ESCOPO', 'Alteração de Escopo / Plano de Trabalho'), ('MISTO', 'Misto (Prazo, Valor e Escopo)'), ('OUTRO', 'Outros Ajustes Formais')], default='PRORROGACAO', max_length=30, verbose_name='Tipo de Aditamento')),
                ('descricao', models.TextField(verbose_name='Objeto / Justificativa da Alteração')),
                ('nova_data_fim', models.DateField(blank=True, null=True, verbose_name='Nova Data de Fim (se houver prorrogação)')),
                ('valor_aditivo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Aditivado (R$)')),
                ('numero_processo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Processo SIPAC/SEI')),
                ('arquivo_pdf', models.TextField(blank=True, max_length=100, null=True, verbose_name='Cópia do Aditivo Assinado (PDF)')),
                ('data_assinatura', models.DateField(blank=True, null=True, verbose_name='Data de Assinatura')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('termo_cooperacao', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cadastros.termocooperacao', verbose_name='Termo de Cooperação')),
            ],
            options={
                'verbose_name': 'historical Aditivo de Termo de Cooperação',
                'verbose_name_plural': 'historical Aditivos de Termo de Cooperação',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTermoAditivo',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, verbose_name='Número do Aditivo')),
                ('tipo_aditivo', models.CharField(choices=[('PRORROGACAO', 'Prorrogação de Vigência (Prazo)'), ('VALOR', 'Acréscimo / Supressão de Recursos (Valor)'), ('ESCOPO', 'Alteração de Escopo / Plano de Trabalho'), ('MISTO', 'Misto (Prazo, Valor e Escopo)'), ('OUTRO', 'Outros Ajustes Formais')], default='PRORROGACAO', max_length=30, verbose_name='Tipo de Aditamento')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Objeto / Justificativa da Alteração')),
                ('nova_data_fim', models.DateField(blank=True, null=True, verbose_name='Nova Data de Término (Se houver prorrogação)')),
                ('valor_aditivo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Aditivado (R$)')),
                ('numero_processo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Processo Administrativo (SIPAC/SEI)')),
                ('arquivo_pdf', models.TextField(blank=True, max_length=100, null=True, verbose_name='Cópia do Aditivo Assinado (PDF)')),
                ('data_assinatura', models.DateField(verbose_name='Data de Assinatura')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('projeto', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cadastros.projetopdi', verbose_name='Projeto PDI Vinculado')),
                ('termo_parceria', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cadastros.termodeparceria', verbose_name='Termo de Parceria')),
            ],
            options={
                'verbose_name': 'historical Termo Aditivo',
                'verbose_name_plural': 'historical Termos Aditivos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
