# Generated by Django 6.0.7 on 2026-09-11 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0076_alter_termoaditivo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='termocooperacao',
            name='data_assinatura',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Assinatura'),
        ),
        migrations.AddField(
            model_name='termodeparceria',
            name='vigencia_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Fim da Vigência'),
        ),
        migrations.AddField(
            model_name='termodeparceria',
            name='vigencia_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Início da Vigência'),
        ),
    ]
