# Generated by Django 6.0.7 on 2026-09-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0078_alter_termodeparceria_tipo_instrumento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termodeparceria',
            name='tipo_instrumento',
            field=models.CharField(choices=[('CONVENIO', 'Convênio de PD&I'), ('ACORDO_PARCERIA', 'Acordo de Parceria para PD&I (Marco Legal CT&I)'), ('TERMO_COOPERACAO', 'Termo de Cooperação'), ('NDA', 'Acordo de Confidencialidade e Sigilo'), ('STE', 'Prestação de Serviços Técnicos Especializados'), ('LICENCIAMENTO', 'Contrato de Licenciamento / Transferência de Tecnologia'), ('COMPARTILHAMENTO', 'Termo de Compartilhamento de Infraestrutura/Laboratório')], default='ACORDO_PARCERIA', max_length=30, verbose_name='Tipo de Instrumento'),
        ),
    ]
