# Generated by Django 6.0.4 on 2026-08-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_servicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROGRAMADA', 'Programada'), ('INICIADA', 'Iniciada'), ('EM_ANDAMENTO', 'Em Andamento'), ('SUSPENSA', 'Suspensa'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20),
        ),
    ]
