# Generated by Django 6.0.4 on 2026-08-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_servicos', '0003_ordemservico_motivo_cancelamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='predio',
            name='area_total_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Área Total (m²)'),
        ),
        migrations.AddField(
            model_name='predio',
            name='armazena_inflamaveis',
            field=models.BooleanField(default=False, verbose_name='Armazena Inflamáveis?'),
        ),
        migrations.AddField(
            model_name='predio',
            name='avcb_numero',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº AVCB'),
        ),
        migrations.AddField(
            model_name='predio',
            name='avcb_validade',
            field=models.DateField(blank=True, null=True, verbose_name='Validade AVCB'),
        ),
        migrations.AddField(
            model_name='predio',
            name='brigada_incendio_ativa',
            field=models.BooleanField(default=False, verbose_name='Brigada de Incêndio Ativa?'),
        ),
        migrations.AddField(
            model_name='predio',
            name='capacidade_pessoas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predio',
            name='finalidade_principal',
            field=models.CharField(blank=True, choices=[('LABORATORIO', 'Laboratório'), ('ADMINISTRATIVO', 'Administrativo'), ('MISTO', 'Misto'), ('GALPAO', 'Galpão de Testes'), ('OUTRO', 'Outro')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='predio',
            name='licenca_ambiental_numero',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº Licença Ambiental'),
        ),
        migrations.AddField(
            model_name='predio',
            name='licenca_ambiental_validade',
            field=models.DateField(blank=True, null=True, verbose_name='Validade Licença Ambiental'),
        ),
        migrations.AddField(
            model_name='predio',
            name='licenca_vigilancia_sanitaria_numero',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº Licença Vig. Sanitária'),
        ),
        migrations.AddField(
            model_name='predio',
            name='licenca_vigilancia_sanitaria_validade',
            field=models.DateField(blank=True, null=True, verbose_name='Validade Vig. Sanitária'),
        ),
        migrations.AddField(
            model_name='predio',
            name='possui_climatizacao_central',
            field=models.BooleanField(default=False, verbose_name='Possui Climatização Central?'),
        ),
        migrations.AddField(
            model_name='predio',
            name='possui_gerador_emergencia',
            field=models.BooleanField(default=False, verbose_name='Possui Gerador de Emergência?'),
        ),
        migrations.AddField(
            model_name='predio',
            name='possui_rede_gases_especiais',
            field=models.BooleanField(default=False, verbose_name='Possui Rede de Gases Especiais?'),
        ),
        migrations.AddField(
            model_name='predio',
            name='possui_sala_limpa',
            field=models.BooleanField(default=False, verbose_name='Possui Sala Limpa?'),
        ),
        migrations.AddField(
            model_name='predio',
            name='possui_subestacao_propria',
            field=models.BooleanField(default=False, verbose_name='Possui Subestação Própria?'),
        ),
        migrations.AddField(
            model_name='predio',
            name='risco_biologico',
            field=models.CharField(blank=True, choices=[('NB1', 'NB-1'), ('NB2', 'NB-2'), ('NB3', 'NB-3'), ('NB4', 'NB-4')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='predio',
            name='risco_quimico',
            field=models.CharField(blank=True, choices=[('BAIXO', 'Baixo'), ('MEDIO', 'Médio'), ('ALTO', 'Alto')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='predio',
            name='tratamento_efluentes_especial',
            field=models.BooleanField(default=False, verbose_name='Possui Tratamento de Efluentes Especial?'),
        ),
    ]
