# Generated by Django 6.0.4 on 2026-08-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_servicos', '0004_predio_area_total_m2_predio_armazena_inflamaveis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='predio',
            name='avcb_arquivo',
            field=models.FileField(blank=True, null=True, upload_to='licencas/avcb/', verbose_name='Arquivo AVCB'),
        ),
        migrations.AddField(
            model_name='predio',
            name='licenca_ambiental_arquivo',
            field=models.FileField(blank=True, null=True, upload_to='licencas/ambiental/', verbose_name='Arquivo Licença Ambiental'),
        ),
        migrations.AddField(
            model_name='predio',
            name='licenca_vigilancia_sanitaria_arquivo',
            field=models.FileField(blank=True, null=True, upload_to='licencas/vigilancia/', verbose_name='Arquivo Vig. Sanitária'),
        ),
    ]
