# Generated by Django 6.0.4 on 2026-08-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_servicos', '0005_predio_avcb_arquivo_predio_licenca_ambiental_arquivo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='predio',
            name='finalidade_principal',
        ),
        migrations.AddField(
            model_name='predio',
            name='capacidade_geracao_solar_kwp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Capacidade Solar (kWp)'),
        ),
        migrations.AddField(
            model_name='predio',
            name='possui_geracao_solar',
            field=models.BooleanField(default=False, verbose_name='Possui Geração Solar?'),
        ),
        migrations.AddField(
            model_name='predio',
            name='quantidade_placas_solares',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade de Placas Solares'),
        ),
        migrations.AddField(
            model_name='predio',
            name='finalidades',
            field=models.ManyToManyField(blank=True, related_name='predios', to='central_servicos.finalidade', verbose_name='Finalidades do Prédio'),
        ),
    ]
