# Generated by Django 6.0.4 on 2026-08-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_servicos', '0006_finalidade_remove_predio_finalidade_principal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predio',
            name='tratamento_efluentes_especial',
        ),
        migrations.AddField(
            model_name='predio',
            name='possui_ete_especial',
            field=models.BooleanField(default=False, verbose_name='Possui ETE Especial/Industrial?'),
        ),
        migrations.AddField(
            model_name='predio',
            name='possui_ete_sanitaria',
            field=models.BooleanField(default=False, verbose_name='Possui ETE Sanitária?'),
        ),
    ]
