# Generated by Django 6.0.4 on 2026-08-02 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_servicos', '0007_remove_predio_tratamento_efluentes_especial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predio',
            name='armazena_inflamaveis',
            field=models.BooleanField(blank=True, null=True, verbose_name='Armazena Inflamáveis?'),
        ),
        migrations.AlterField(
            model_name='predio',
            name='brigada_incendio_ativa',
            field=models.BooleanField(blank=True, null=True, verbose_name='Brigada de Incêndio Ativa?'),
        ),
        migrations.AlterField(
            model_name='predio',
            name='possui_climatizacao_central',
            field=models.BooleanField(blank=True, null=True, verbose_name='Possui Climatização Central?'),
        ),
        migrations.AlterField(
            model_name='predio',
            name='possui_ete_especial',
            field=models.BooleanField(blank=True, null=True, verbose_name='Possui ETE Especial/Industrial?'),
        ),
        migrations.AlterField(
            model_name='predio',
            name='possui_ete_sanitaria',
            field=models.BooleanField(blank=True, null=True, verbose_name='Possui ETE Sanitária?'),
        ),
        migrations.AlterField(
            model_name='predio',
            name='possui_geracao_solar',
            field=models.BooleanField(blank=True, null=True, verbose_name='Possui Geração Solar?'),
        ),
        migrations.AlterField(
            model_name='predio',
            name='possui_gerador_emergencia',
            field=models.BooleanField(blank=True, null=True, verbose_name='Possui Gerador de Emergência?'),
        ),
        migrations.AlterField(
            model_name='predio',
            name='possui_rede_gases_especiais',
            field=models.BooleanField(blank=True, null=True, verbose_name='Possui Rede de Gases Especiais?'),
        ),
        migrations.AlterField(
            model_name='predio',
            name='possui_sala_limpa',
            field=models.BooleanField(blank=True, null=True, verbose_name='Possui Sala Limpa?'),
        ),
        migrations.AlterField(
            model_name='predio',
            name='possui_subestacao_propria',
            field=models.BooleanField(blank=True, null=True, verbose_name='Possui Subestação Própria?'),
        ),
    ]
