# Generated by Django 6.0.4 on 2026-08-11 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_servicos', '0008_alter_predio_armazena_inflamaveis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Tipo de Ativo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tipo de Ativo',
                'verbose_name_plural': 'Tipos de Ativos',
                'ordering': ['nome'],
            },
        ),
        migrations.RemoveField(
            model_name='ativopredial',
            name='nome',
        ),
        migrations.AddField(
            model_name='ativopredial',
            name='nome_apelido',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome/Apelido'),
        ),
        migrations.AddField(
            model_name='ativopredial',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Série'),
        ),
        migrations.AlterField(
            model_name='ativopredial',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='ativopredial',
            name='patrimonio',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Patrimônio'),
        ),
        migrations.AddField(
            model_name='ativopredial',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ativos', to='central_servicos.tipoativo', verbose_name='Tipo de Ativo'),
        ),
    ]
