# Generated by Django 6.0.7 on 2026-08-12 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_servicos', '0009_tipoativo_remove_ativopredial_nome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaElemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Piso, Parede, Janela, Forro', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria de Elemento',
                'verbose_name_plural': 'Categorias de Elementos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoAmbiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Tipo de Ambiente')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tipo de Ambiente',
                'verbose_name_plural': 'Tipos de Ambiente',
                'ordering': ['nome'],
            },
        ),
        migrations.RemoveField(
            model_name='ativopredial',
            name='sala',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='sala',
        ),
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('localizacao', models.CharField(choices=[('INTERNO', 'Área Interna'), ('EXTERNO', 'Área Externa')], default='INTERNO', max_length=10)),
                ('andar', models.ForeignKey(blank=True, help_text='Deixe em branco para áreas externas', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambientes', to='central_servicos.andar')),
                ('predio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambientes', to='central_servicos.predio')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ambientes', to='central_servicos.tipoambiente')),
            ],
        ),
        migrations.AddField(
            model_name='ativopredial',
            name='ambiente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ativos', to='central_servicos.ambiente', verbose_name='Ambiente'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='ambiente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_servico', to='central_servicos.ambiente', verbose_name='Ambiente'),
        ),
        migrations.CreateModel(
            name='TipoElemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Piso Frio, Piso Acarpetado, Parede Drywall', max_length=100)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos', to='central_servicos.categoriaelemento')),
            ],
            options={
                'verbose_name': 'Tipo de Elemento',
                'verbose_name_plural': 'Tipos de Elementos',
                'ordering': ['categoria__nome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ElementoConstrutivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_m2', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Área (m²)')),
                ('detalhes', models.TextField(blank=True, help_text='Especificações ou detalhes para cálculo da IN 05/2017', null=True)),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementos_construtivos', to='central_servicos.ambiente')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='central_servicos.tipoelemento')),
            ],
        ),
        migrations.DeleteModel(
            name='Sala',
        ),
    ]
