# Generated by Django 6.0.7 on 2026-08-13 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_servicos', '0011_historicalambiente_historicalandar_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ambiente',
            options={'ordering': ['ordem']},
        ),
        migrations.AlterModelOptions(
            name='andar',
            options={'ordering': ['ordem']},
        ),
        migrations.AddField(
            model_name='ambiente',
            name='ordem',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem'),
        ),
        migrations.AddField(
            model_name='andar',
            name='ordem',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem'),
        ),
        migrations.AddField(
            model_name='historicalambiente',
            name='ordem',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem'),
        ),
        migrations.AddField(
            model_name='historicalandar',
            name='ordem',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem'),
        ),
    ]
