# Generated by Django 6.0.7 on 2026-08-13 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_servicos', '0012_alter_ambiente_options_alter_andar_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='predio',
            options={'ordering': ['ordem']},
        ),
        migrations.AddField(
            model_name='historicalpredio',
            name='ordem',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem'),
        ),
        migrations.AddField(
            model_name='predio',
            name='ordem',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem'),
        ),
    ]
