# Generated by Django 6.0.7 on 2026-08-25 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_servicos', '0014_categoriaelemento_descricao_finalidade_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambiente',
            name='ambiente_pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_ambientes', to='central_servicos.ambiente', verbose_name='Ambiente Pai (Laboratório/Setor Maior)'),
        ),
        migrations.AddField(
            model_name='ambiente',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ambiente Ativo?'),
        ),
        migrations.AddField(
            model_name='historicalambiente',
            name='ambiente_pai',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='central_servicos.ambiente', verbose_name='Ambiente Pai (Laboratório/Setor Maior)'),
        ),
        migrations.AddField(
            model_name='historicalambiente',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ambiente Ativo?'),
        ),
    ]
