# Generated by Django 6.0.7 on 2026-08-27 19:48

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_servicos', '0015_ambiente_ambiente_pai_ambiente_ativo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ambiente',
            name='area_piso_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Área do Piso (m²)'),
        ),
        migrations.AddField(
            model_name='ambiente',
            name='coordenadas_mapa',
            field=models.JSONField(blank=True, help_text='Coordenadas do polígono no mapa', null=True),
        ),
        migrations.AddField(
            model_name='ambiente',
            name='pe_direito',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sobrescreve a altura padrão do andar se preenchido', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='ambiente',
            name='perimetro_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Perímetro (m)'),
        ),
        migrations.AddField(
            model_name='andar',
            name='pe_direito_padrao',
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=5, verbose_name='Pé-Direito Padrão (m)'),
        ),
        migrations.AddField(
            model_name='historicalambiente',
            name='area_piso_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Área do Piso (m²)'),
        ),
        migrations.AddField(
            model_name='historicalambiente',
            name='coordenadas_mapa',
            field=models.JSONField(blank=True, help_text='Coordenadas do polígono no mapa', null=True),
        ),
        migrations.AddField(
            model_name='historicalambiente',
            name='pe_direito',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sobrescreve a altura padrão do andar se preenchido', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='historicalambiente',
            name='perimetro_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Perímetro (m)'),
        ),
        migrations.AddField(
            model_name='historicalandar',
            name='pe_direito_padrao',
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=5, verbose_name='Pé-Direito Padrão (m)'),
        ),
        migrations.CreateModel(
            name='HistoricalPlantaBaixa',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('imagem', models.TextField(help_text='Utilize formatos web otimizados (PNG, WebP, SVG)', max_length=100)),
                ('descricao', models.CharField(help_text='Ex: As-Built Original 2024', max_length=150)),
                ('vigente', models.BooleanField(default=True)),
                ('fator_escala', models.DecimalField(decimal_places=4, default=1.0, help_text='Quantos pixels representam 1 metro na imagem original', max_digits=10)),
                ('data_upload', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('andar', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='central_servicos.andar')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Planta Baixa',
                'verbose_name_plural': 'historical Plantas Baixas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PlantaBaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(help_text='Utilize formatos web otimizados (PNG, WebP, SVG)', upload_to='plantas_raster/')),
                ('descricao', models.CharField(help_text='Ex: As-Built Original 2024', max_length=150)),
                ('vigente', models.BooleanField(default=True)),
                ('fator_escala', models.DecimalField(decimal_places=4, default=1.0, help_text='Quantos pixels representam 1 metro na imagem original', max_digits=10)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('andar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantas', to='central_servicos.andar')),
            ],
            options={
                'verbose_name': 'Planta Baixa',
                'verbose_name_plural': 'Plantas Baixas',
                'ordering': ['-data_upload'],
            },
        ),
        migrations.AddField(
            model_name='ambiente',
            name='planta_baixa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambientes', to='central_servicos.plantabaixa'),
        ),
        migrations.AddField(
            model_name='historicalambiente',
            name='planta_baixa',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='central_servicos.plantabaixa'),
        ),
    ]
