# Generated by Django 6.0.7 on 2026-09-08 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_servicos', '0016_ambiente_area_piso_m2_ambiente_coordenadas_mapa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ambiente',
            name='data_inativacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Inativação'),
        ),
        migrations.AddField(
            model_name='ambiente',
            name='inativado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambientes_inativados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ambiente',
            name='motivo_inativacao',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo da Inativação / Mutação'),
        ),
        migrations.AddField(
            model_name='historicalambiente',
            name='data_inativacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Inativação'),
        ),
        migrations.AddField(
            model_name='historicalambiente',
            name='inativado_por',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalambiente',
            name='motivo_inativacao',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo da Inativação / Mutação'),
        ),
        migrations.AlterField(
            model_name='ambiente',
            name='ambiente_pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_ambientes', to='central_servicos.ambiente', verbose_name='Ambiente Pai (Laboratório/Setor Maior)'),
        ),
        migrations.AlterField(
            model_name='elementoconstrutivo',
            name='ambiente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elementos_construtivos', to='central_servicos.ambiente'),
        ),
    ]
