# Generated by Django 6.0.4 on 2026-05-19 22:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstituicaoParceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Instituição')),
                ('sigla', models.CharField(max_length=20, unique=True)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
            ],
            options={
                'verbose_name': 'Instituição Parceira',
                'verbose_name_plural': 'Instituições Parceiras',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_convenio', models.CharField(max_length=50, unique=True, verbose_name='Número do Convênio')),
                ('objeto', models.TextField(blank=True, null=True, verbose_name='Objeto / Descrição')),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='convenios', to='gestao_projetos.instituicaoparceira')),
            ],
            options={
                'verbose_name': 'Convênio',
                'verbose_name_plural': 'Convênios',
            },
        ),
        migrations.CreateModel(
            name='ProjetoPDI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='Nome do Projeto')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('FINALIZADO', 'Finalizado')], default='ATIVO', max_length=20)),
                ('convenio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos', to='gestao_projetos.convenio')),
            ],
            options={
                'verbose_name': 'Projeto PDI',
                'verbose_name_plural': 'Projetos PDI',
            },
        ),
        migrations.CreateModel(
            name='EquipeProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.CharField(choices=[('CPO', 'Coordenador de Projeto (CPO)'), ('GPA', 'Gestor de Programa (GPA)'), ('GPO', 'Gestor de Projeto (GPO)'), ('PEQ', 'Pesquisador (PEQ)'), ('EST', 'Estudante / Bolsista (EST)'), ('ADM', 'Apoio Administrativo (ADM)'), ('CLE', 'Colaborador Externo (CLE)')], max_length=4)),
                ('tipo_bolsa', models.CharField(choices=[('BP', 'Bolsa de Parceria (BP)'), ('BI', 'Bolsa Institucional (BI)'), ('SB', 'Sem Bolsa / Contrapartida')], default='BP', max_length=2)),
                ('carga_horaria_semanal', models.PositiveIntegerField(default=20)),
                ('data_inicio', models.DateField(default=django.utils.timezone.now)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to='gestao_projetos.pessoa')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros_equipe', to='gestao_projetos.projetopdi')),
            ],
            options={
                'verbose_name': 'Membro da Equipe',
                'verbose_name_plural': 'Membros das Equipes',
            },
        ),
    ]
