# Generated by Django 6.0.7 on 2026-08-31 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0050_termocooperacao_projetopdi_termo_cooperacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Aguardando Assinatura'), ('CONCLUIDO', 'Assinado / Concluído')], default='PENDENTE', max_length=15)),
                ('versao', models.PositiveIntegerField(default=1, verbose_name='Versão do Relatório')),
                ('periodo_inicio', models.DateField(verbose_name='Período Início')),
                ('periodo_fim', models.DateField(verbose_name='Período Fim')),
                ('carga_horaria_periodo', models.PositiveIntegerField(verbose_name='Carga Horária do Período')),
                ('ocorrencias', models.TextField(blank=True, help_text="Injetado no bloco 'Ocorrências' do relatório. Deixe em branco para 'Nenhuma'.", null=True)),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='projetos/relatorios_assinados/', verbose_name='Relatório Assinado (PDF)')),
                ('cumpriu_carga_horaria', models.BooleanField(default=True, verbose_name='Cumpriu com a Carga Horária')),
                ('parecer_coordenador', models.TextField(blank=True, null=True, verbose_name='Demais informações pertinentes (Parecer)')),
                ('bolsista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relatorios_bolsista', to='cadastros.bolsistaprojeto')),
                ('conta_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relatorios_pagos', to='cadastros.contabancaria', verbose_name='Conta Pagadora / Fonte de Recurso')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('macroentregas', models.ManyToManyField(blank=True, related_name='relatorios', to='cadastros.macroentrega', verbose_name='Macroentregas Associadas')),
                ('parcela_referencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='cadastros.parcela', verbose_name='Parcela de Referência')),
                ('termo_bolsa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_termo', to='cadastros.termobolsa')),
            ],
            options={
                'verbose_name': 'Relatório de Atividade',
                'verbose_name_plural': 'Relatórios de Atividades',
                'db_table': 'argus_relatorio_atividade',
                'unique_together': {('termo_bolsa', 'parcela_referencia')},
            },
        ),
        migrations.CreateModel(
            name='ItemAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_execucao', models.CharField(max_length=50)),
                ('descricao', models.TextField(verbose_name='Descrição da Tarefa Realizada')),
                ('carga_horaria_percentual', models.CharField(default='100%', max_length=10)),
                ('atividade_mae', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tarefas_executadas', to='cadastros.atividadeplanoacao')),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_atividade', to='gestao_projetos.relatorioatividade')),
            ],
        ),
    ]
