# Generated by Django 6.1.1 on 2026-09-11 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncaoInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ex: DIRETOR_POLO, REITOR, COORD_RH', max_length=50, unique=True, verbose_name='Código da Função')),
                ('nome_cargo', models.CharField(max_length=255, verbose_name='Nome do Cargo / Função')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Função Institucional',
                'verbose_name_plural': 'Funções Institucionais',
                'ordering': ['nome_cargo'],
            },
        ),
        migrations.CreateModel(
            name='OcupacaoFuncao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_externo', models.CharField(blank=True, max_length=255, verbose_name='Nome Externo (quando não cadastrado como PessoaFisica)')),
                ('prioridade', models.IntegerField(choices=[(0, 'Titular'), (1, '1º Substituto'), (2, '2º Substituto'), (3, '3º Substituto')], default=0, verbose_name='Prioridade de Suplência')),
                ('portaria_designacao', models.CharField(blank=True, help_text='Ex: Portaria 061/GR/IFAM', max_length=100, verbose_name='Portaria de Designação')),
                ('sufixo_cargo', models.CharField(blank=True, help_text="Ex: 'Substituto', '1º Substituto'. Preenchido automaticamente se vazio.", max_length=100, verbose_name='Sufixo do Cargo')),
                ('ativo', models.BooleanField(default=True)),
                ('funcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocupacoes', to='gestao_projetos.funcaoinstitucional', verbose_name='Função Institucional')),
                ('pessoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocupacoes_funcao', to='cadastros.pessoafisica', verbose_name='Pessoa Física')),
            ],
            options={
                'verbose_name': 'Ocupação de Função',
                'verbose_name_plural': 'Ocupações de Funções',
                'ordering': ['funcao', 'prioridade'],
                'unique_together': {('funcao', 'prioridade')},
            },
        ),
        migrations.CreateModel(
            name='AfastamentoExercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data de Início do Afastamento')),
                ('data_fim', models.DateField(verbose_name='Data de Fim do Afastamento')),
                ('motivo', models.CharField(choices=[('FERIAS', 'Férias'), ('LICENCA_MEDICA', 'Licença Médica'), ('MISSAO', 'Missão Institucional'), ('LICENCA_CAPACITACAO', 'Licença para Capacitação'), ('OUTRO', 'Outro')], default='FERIAS', max_length=25, verbose_name='Motivo')),
                ('documento_comprobatorio', models.CharField(blank=True, help_text='Número da portaria, memorando ou despacho autorizando o afastamento.', max_length=200, verbose_name='Documento Comprobatório')),
                ('ativo', models.BooleanField(default=True)),
                ('ocupacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='afastamentos', to='gestao_projetos.ocupacaofuncao', verbose_name='Ocupação')),
            ],
            options={
                'verbose_name': 'Afastamento de Exercício',
                'verbose_name_plural': 'Afastamentos de Exercício',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='RelatorioAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Rascunho / Em Elaboração'), ('EM_ANALISE', 'Submetido / Aguardando Atesto SIAPE'), ('CONCLUIDO', 'Homologado / Atestado')], default='PENDENTE', max_length=15)),
                ('versao', models.PositiveIntegerField(default=1, verbose_name='Versão do Relatório')),
                ('periodo_inicio', models.DateField(verbose_name='Período Início')),
                ('periodo_fim', models.DateField(verbose_name='Período Fim')),
                ('carga_horaria_periodo', models.PositiveIntegerField(verbose_name='Carga Horária do Período')),
                ('ocorrencias', models.TextField(blank=True, help_text="Injetado no bloco 'Ocorrências' do relatório. Deixe em branco para 'Nenhuma'.", null=True)),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='projetos/relatorios_assinados/', verbose_name='Relatório Assinado (PDF)')),
                ('cumpriu_carga_horaria', models.BooleanField(default=True, verbose_name='Cumpriu com a Carga Horária')),
                ('parecer_coordenador', models.TextField(blank=True, null=True, verbose_name='Demais informações pertinentes (Parecer)')),
                ('data_atesto', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora do Atesto')),
                ('siape_atesto', models.CharField(blank=True, max_length=20, null=True, verbose_name='Matrícula SIAPE do Servidor Atestante')),
                ('atestado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relatorios_atestados', to=settings.AUTH_USER_MODEL, verbose_name='Atestado por (Servidor Efetivo)')),
                ('bolsista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relatorios_bolsista', to='cadastros.bolsistaprojeto')),
                ('conta_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relatorios_pagos', to='cadastros.contabancaria', verbose_name='Conta Pagadora / Fonte de Recurso')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('macroentregas', models.ManyToManyField(blank=True, related_name='relatorios', to='cadastros.macroentrega', verbose_name='Macroentregas Associadas')),
                ('parcela_referencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='cadastros.parcela', verbose_name='Parcela de Referência')),
                ('termo_bolsa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_termo', to='cadastros.termobolsa')),
            ],
            options={
                'verbose_name': 'Relatório de Atividade',
                'verbose_name_plural': 'Relatórios de Atividades',
                'db_table': 'argus_relatorio_atividade',
                'unique_together': {('termo_bolsa', 'parcela_referencia')},
            },
        ),
        migrations.CreateModel(
            name='ItemAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_execucao', models.CharField(max_length=50)),
                ('descricao', models.TextField(verbose_name='Descrição da Tarefa Realizada')),
                ('carga_horaria_percentual', models.CharField(default='100%', max_length=10)),
                ('atividade_mae', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tarefas_executadas', to='cadastros.atividadeplanoacao')),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_atividade', to='gestao_projetos.relatorioatividade')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateDocumentoConveniar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Template')),
                ('tipo', models.CharField(choices=[('OFICIO_EQUIPE', 'Ofício de Pagamento da Equipe'), ('OFICIO_COORDENADOR', 'Ofício de Pagamento do Coordenador'), ('RECIBO', 'Recibo de Pagamento'), ('DECLARACAO', 'Declaração de Vínculo'), ('OUTRO', 'Outro Documento Institucional')], max_length=30, verbose_name='Tipo do Documento')),
                ('descricao', models.TextField(verbose_name='Descrição / Orientações de Uso')),
                ('arquivo_docx', models.FileField(upload_to='templates_conveniar/', verbose_name='Arquivo DOCX (Matriz)')),
                ('versao', models.CharField(default='1.0', max_length=20, verbose_name='Versão')),
                ('ativo', models.BooleanField(default=True, verbose_name='Template Ativo')),
                ('tags_disponiveis', models.TextField(blank=True, help_text='Lista das variáveis {{ tag }} suportadas por este template, uma por linha.', null=True, verbose_name='Tags Disponíveis')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates_atualizados', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Template de Documento Conveniar',
                'verbose_name_plural': 'Templates de Documentos Conveniar',
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.CreateModel(
            name='RegraAlcadaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('OFICIO_EQUIPE', 'Ofício de Pagamento da Equipe'), ('OFICIO_COORDENADOR', 'Ofício de Pagamento do Coordenador'), ('OFICIO_COORD_DIRETOR_CAMPUS', 'Ofício de Pagamento do Coordenador (Diretor de Campus)'), ('CONTRATACAO_BOLSISTA', 'Contratação de Bolsista'), ('OUTRO', 'Outro')], max_length=35, verbose_name='Tipo do Documento')),
                ('condicao_beneficiario', models.CharField(choices=[('QUALQUER_BOLSISTA', 'Qualquer Bolsista'), ('COORDENADOR_PROJETO', 'Coordenador do Projeto (não Diretor de Campus)'), ('COORDENADOR_E_DIRETOR_CAMPUS', 'Coordenador que é Diretor-Geral de Campus')], default='QUALQUER_BOLSISTA', max_length=35, verbose_name='Condição do Beneficiário')),
                ('exige_siape', models.BooleanField(default=True, verbose_name='Exige SIAPE do Signatário?')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição / Justificativa Legal')),
                ('ativo', models.BooleanField(default=True)),
                ('funcao_requisitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regras_como_requisitante', to='gestao_projetos.funcaoinstitucional', verbose_name='Função do Signatário Requisitante')),
                ('funcao_visto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regras_como_visto', to='gestao_projetos.funcaoinstitucional', verbose_name='Função do Visto (Ciência)')),
            ],
            options={
                'verbose_name': 'Regra de Alçada de Documento',
                'verbose_name_plural': 'Regras de Alçada de Documentos',
                'ordering': ['tipo_documento', 'condicao_beneficiario'],
                'unique_together': {('tipo_documento', 'condicao_beneficiario')},
            },
        ),
        migrations.CreateModel(
            name='OficioSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sequencial', models.PositiveIntegerField(verbose_name='Número Sequencial')),
                ('ano', models.PositiveIntegerField(verbose_name='Ano do Ofício')),
                ('tipo', models.CharField(choices=[('EQUIPE', 'Ofício de Pagamento da Equipe'), ('COORDENADOR', 'Ofício de Pagamento do Coordenador')], max_length=20, verbose_name='Tipo do Ofício')),
                ('competencia', models.DateField(verbose_name='Mês de Competência (dia 1)')),
                ('signatario_nome', models.CharField(max_length=255, verbose_name='Nome do Signatário (Requisitante)')),
                ('signatario_cargo', models.CharField(max_length=255, verbose_name='Cargo do Signatário')),
                ('coordenador_is_diretor_campus', models.BooleanField(default=False, help_text='Quando True, o Reitor assina como Requisitante em vez do Diretor do Polo.', verbose_name='Coordenador é Diretor-Geral de Campus?')),
                ('visto_nome', models.CharField(blank=True, max_length=255, verbose_name='Nome do Visto (Ciência)')),
                ('visto_cargo', models.CharField(blank=True, max_length=255, verbose_name='Cargo do Visto')),
                ('arquivo_docx', models.FileField(blank=True, null=True, upload_to='oficios_conveniar/', verbose_name='Ofício Gerado (.docx)')),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='oficios_conveniar/', verbose_name='Ofício Assinado (.pdf)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oficios_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('parcelas', models.ManyToManyField(blank=True, related_name='oficios_conveniar', to='cadastros.parcela', verbose_name='Parcelas Incluídas')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oficios_solicitacao', to='cadastros.projetopdi', verbose_name='Projeto')),
                ('template_utilizado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oficios_gerados', to='gestao_projetos.templatedocumentoconveniar', verbose_name='Template Utilizado')),
            ],
            options={
                'verbose_name': 'Ofício de Solicitação',
                'verbose_name_plural': 'Ofícios de Solicitação',
                'ordering': ['-criado_em'],
                'unique_together': {('projeto', 'numero_sequencial', 'ano')},
            },
        ),
    ]
