# Generated by Django 6.0.4 on 2026-07-29 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_convenio_instituicaoparceira_and_more'),
        ('gestao_projetos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convenio',
            name='instituicao',
        ),
        migrations.RemoveField(
            model_name='projetopdi',
            name='convenio',
        ),
        migrations.RemoveField(
            model_name='equipeprojeto',
            name='pessoa',
        ),
        migrations.RemoveField(
            model_name='equipeprojeto',
            name='projeto',
        ),
        migrations.CreateModel(
            name='Bolsista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('rg', models.CharField(max_length=20)),
                ('funcao', models.CharField(max_length=100)),
                ('termo_bolsa', models.CharField(max_length=50)),
                ('carga_horaria_total', models.PositiveIntegerField()),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bolsistas_vinculados', to='cadastros.projetopdi')),
            ],
            options={
                'verbose_name': 'Bolsista',
                'db_table': 'argus_bolsista',
            },
        ),
        migrations.CreateModel(
            name='MembroEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('COORDENADOR', 'Coordenador do Projeto'), ('GESTOR', 'Gestor de Projeto'), ('ANALISTA', 'Analista Integrador'), ('AUX_ADM', 'Auxiliar Administrativo')], max_length=15)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipe_pdi', to='cadastros.projetopdi')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membro da Equipe',
                'verbose_name_plural': 'Membros da Equipe',
                'db_table': 'argus_membro_equipe',
                'unique_together': {('projeto', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='RelatorioAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('CONCLUIDO', 'Pronto para Download')], default='RASCUNHO', max_length=15)),
                ('parcela', models.PositiveIntegerField()),
                ('macroentrega', models.PositiveIntegerField()),
                ('periodo_inicio', models.DateField()),
                ('periodo_fim', models.DateField()),
                ('carga_horaria_periodo', models.PositiveIntegerField()),
                ('ocorrencias', models.TextField(blank=True, help_text="Injetado no bloco 'Ocorrências' do relatório. Deixe em branco para 'Nenhuma'.", null=True)),
                ('bolsista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_bolsista', to='gestao_projetos.bolsista')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relatório de Atividade',
                'verbose_name_plural': 'Relatórios de Atividades',
                'db_table': 'argus_relatorio_atividade',
                'unique_together': {('bolsista', 'parcela')},
            },
        ),
        migrations.CreateModel(
            name='ItemAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_atividade', models.PositiveIntegerField()),
                ('periodo_execucao', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('carga_horaria_percentual', models.CharField(blank=True, max_length=10, null=True)),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_atividade', to='gestao_projetos.relatorioatividade')),
            ],
            options={
                'verbose_name': 'Item de Atividade',
                'verbose_name_plural': 'Itens de Atividades',
                'db_table': 'argus_item_atividade',
                'ordering': ['numero_atividade'],
            },
        ),
        migrations.DeleteModel(
            name='InstituicaoParceira',
        ),
        migrations.DeleteModel(
            name='Convenio',
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
        migrations.DeleteModel(
            name='EquipeProjeto',
        ),
        migrations.DeleteModel(
            name='ProjetoPDI',
        ),
    ]
