# Generated by Django 6.0.7 on 2026-09-04 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0063_populate_existing_parcelas_financial_data'),
        ('gestao_projetos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateDocumentoConveniar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Template')),
                ('tipo', models.CharField(choices=[('OFICIO_EQUIPE', 'Ofício de Pagamento da Equipe'), ('OFICIO_COORDENADOR', 'Ofício de Pagamento do Coordenador'), ('RECIBO', 'Recibo de Pagamento'), ('DECLARACAO', 'Declaração de Vínculo'), ('OUTRO', 'Outro Documento Institucional')], max_length=30, verbose_name='Tipo do Documento')),
                ('descricao', models.TextField(verbose_name='Descrição / Orientações de Uso')),
                ('arquivo_docx', models.FileField(upload_to='templates_conveniar/', verbose_name='Arquivo DOCX (Matriz)')),
                ('versao', models.CharField(default='1.0', max_length=20, verbose_name='Versão')),
                ('ativo', models.BooleanField(default=True, verbose_name='Template Ativo')),
                ('tags_disponiveis', models.TextField(blank=True, help_text='Lista das variáveis {{ tag }} suportadas por este template, uma por linha.', null=True, verbose_name='Tags Disponíveis')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates_atualizados', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Template de Documento Conveniar',
                'verbose_name_plural': 'Templates de Documentos Conveniar',
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.CreateModel(
            name='OficioSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sequencial', models.PositiveIntegerField(verbose_name='Número Sequencial')),
                ('ano', models.PositiveIntegerField(verbose_name='Ano do Ofício')),
                ('tipo', models.CharField(choices=[('EQUIPE', 'Ofício de Pagamento da Equipe'), ('COORDENADOR', 'Ofício de Pagamento do Coordenador')], max_length=20, verbose_name='Tipo do Ofício')),
                ('competencia', models.DateField(verbose_name='Mês de Competência (dia 1)')),
                ('signatario_nome', models.CharField(max_length=255, verbose_name='Nome do Signatário (Requisitante)')),
                ('signatario_cargo', models.CharField(max_length=255, verbose_name='Cargo do Signatário')),
                ('coordenador_is_diretor_campus', models.BooleanField(default=False, help_text='Quando True, o Reitor assina como Requisitante em vez do Diretor do Polo.', verbose_name='Coordenador é Diretor-Geral de Campus?')),
                ('visto_nome', models.CharField(blank=True, max_length=255, verbose_name='Nome do Visto (Ciência)')),
                ('visto_cargo', models.CharField(blank=True, max_length=255, verbose_name='Cargo do Visto')),
                ('arquivo_docx', models.FileField(blank=True, null=True, upload_to='oficios_conveniar/', verbose_name='Ofício Gerado (.docx)')),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='oficios_conveniar/', verbose_name='Ofício Assinado (.pdf)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oficios_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('parcelas', models.ManyToManyField(blank=True, related_name='oficios_conveniar', to='cadastros.parcela', verbose_name='Parcelas Incluídas')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oficios_solicitacao', to='cadastros.projetopdi', verbose_name='Projeto')),
                ('template_utilizado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oficios_gerados', to='gestao_projetos.templatedocumentoconveniar', verbose_name='Template Utilizado')),
            ],
            options={
                'verbose_name': 'Ofício de Solicitação',
                'verbose_name_plural': 'Ofícios de Solicitação',
                'ordering': ['-criado_em'],
                'unique_together': {('projeto', 'numero_sequencial', 'ano')},
            },
        ),
    ]
