# Generated by Django 6.0.7 on 2026-09-04 21:56

import django.db.models.deletion
from django.db import migrations, models


def seed_funcoes_e_ocupacoes(apps, schema_editor):
    """
    Carga inicial das funções institucionais e seus titulares/substitutos
    conforme portarias vigentes do Polo de Inovação IFAM/Manaus.
    """
    FuncaoInstitucional = apps.get_model('gestao_projetos', 'FuncaoInstitucional')
    OcupacaoFuncao = apps.get_model('gestao_projetos', 'OcupacaoFuncao')
    RegraAlcadaDocumento = apps.get_model('gestao_projetos', 'RegraAlcadaDocumento')

    diretor_polo, _ = FuncaoInstitucional.objects.get_or_create(
        codigo='DIRETOR_POLO',
        defaults={
            'nome_cargo': 'Diretor-Geral do Polo de Inovação IFAM/Manaus',
            'descricao': 'Função de Direção do Polo de Inovação — IFAM Campus Manaus Centro',
        }
    )
    reitor, _ = FuncaoInstitucional.objects.get_or_create(
        codigo='REITOR',
        defaults={
            'nome_cargo': 'Reitor do IFAM',
            'descricao': 'Reitor do Instituto Federal de Educação, Ciência e Tecnologia do Amazonas',
        }
    )
    coord_rh, _ = FuncaoInstitucional.objects.get_or_create(
        codigo='COORD_RH',
        defaults={
            'nome_cargo': 'Coordenador de Gestão de Pessoas do Polo',
            'descricao': 'Coordenação responsável pela gestão de RH do Polo de Inovação',
        }
    )
    dir_admin_fin, _ = FuncaoInstitucional.objects.get_or_create(
        codigo='DIRETOR_ADMIN_FINANCEIRO',
        defaults={
            'nome_cargo': 'Diretor Administrativo e Financeiro do Polo',
            'descricao': 'Diretoria Administrativa e Financeira do Polo de Inovação',
        }
    )

    # Ocupações — Direção-Geral do Polo
    OcupacaoFuncao.objects.get_or_create(
        funcao=diretor_polo, prioridade=0,
        defaults={'nome_externo': 'Alyson de Jesus dos Santos', 'portaria_designacao': 'Portaria 061/GR/IFAM', 'sufixo_cargo': ''}
    )
    OcupacaoFuncao.objects.get_or_create(
        funcao=diretor_polo, prioridade=1,
        defaults={'nome_externo': 'Alexandre Lopes Martiniano', 'portaria_designacao': 'Portaria 366/GR/IFAM', 'sufixo_cargo': '1º Substituto'}
    )

    # Ocupações — Reitoria
    OcupacaoFuncao.objects.get_or_create(
        funcao=reitor, prioridade=0,
        defaults={'nome_externo': 'Jaime Cavalcante Alves', 'portaria_designacao': 'Decreto Presidencial de 21/06/2023', 'sufixo_cargo': ''}
    )

    # Ocupações — Coordenação de RH
    OcupacaoFuncao.objects.get_or_create(
        funcao=coord_rh, prioridade=0,
        defaults={'nome_externo': 'Marcelo Rodrigues Tomaz', 'portaria_designacao': 'Portaria 216/2025', 'sufixo_cargo': ''}
    )
    OcupacaoFuncao.objects.get_or_create(
        funcao=coord_rh, prioridade=1,
        defaults={'nome_externo': 'Geziel Sena Colares', 'portaria_designacao': 'Portaria 1.211/2026', 'sufixo_cargo': '1º Substituto'}
    )

    # Ocupações — Diretoria Administrativa e Financeira
    OcupacaoFuncao.objects.get_or_create(
        funcao=dir_admin_fin, prioridade=0,
        defaults={'nome_externo': 'Alexandre Lopes Martiniano', 'portaria_designacao': 'Portaria 1.682/GR/IFAM', 'sufixo_cargo': ''}
    )

    # Regras de Alçada
    RegraAlcadaDocumento.objects.get_or_create(
        tipo_documento='OFICIO_EQUIPE', condicao_beneficiario='QUALQUER_BOLSISTA',
        defaults={
            'funcao_requisitante': diretor_polo, 'funcao_visto': coord_rh, 'exige_siape': True,
            'descricao': 'Ofícios de equipe assinados pelo Diretor-Geral do Polo, visto Coord. RH.',
        }
    )
    RegraAlcadaDocumento.objects.get_or_create(
        tipo_documento='OFICIO_COORDENADOR', condicao_beneficiario='COORDENADOR_PROJETO',
        defaults={
            'funcao_requisitante': diretor_polo, 'funcao_visto': None, 'exige_siape': True,
            'descricao': 'Ofício do Coordenador (não Diretor de Campus) assinado pelo Diretor do Polo.',
        }
    )
    RegraAlcadaDocumento.objects.get_or_create(
        tipo_documento='OFICIO_COORD_DIRETOR_CAMPUS', condicao_beneficiario='COORDENADOR_E_DIRETOR_CAMPUS',
        defaults={
            'funcao_requisitante': reitor, 'funcao_visto': diretor_polo, 'exige_siape': True,
            'descricao': 'Coordenador Diretor de Campus: Reitor assina como Requisitante, Diretor do Polo dá o Visto.',
        }
    )


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0063_populate_existing_parcelas_financial_data'),
        ('gestao_projetos', '0002_templatedocumentoconveniar_oficiosolicitacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncaoInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ex: DIRETOR_POLO, REITOR, COORD_RH', max_length=50, unique=True, verbose_name='Código da Função')),
                ('nome_cargo', models.CharField(max_length=255, verbose_name='Nome do Cargo / Função')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Função Institucional',
                'verbose_name_plural': 'Funções Institucionais',
                'ordering': ['nome_cargo'],
            },
        ),
        migrations.CreateModel(
            name='OcupacaoFuncao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_externo', models.CharField(blank=True, max_length=255, verbose_name='Nome Externo (quando não cadastrado como PessoaFisica)')),
                ('prioridade', models.IntegerField(choices=[(0, 'Titular'), (1, '1º Substituto'), (2, '2º Substituto'), (3, '3º Substituto')], default=0, verbose_name='Prioridade de Suplência')),
                ('portaria_designacao', models.CharField(blank=True, help_text='Ex: Portaria 061/GR/IFAM', max_length=100, verbose_name='Portaria de Designação')),
                ('sufixo_cargo', models.CharField(blank=True, help_text="Ex: 'Substituto', '1º Substituto'. Preenchido automaticamente se vazio.", max_length=100, verbose_name='Sufixo do Cargo')),
                ('ativo', models.BooleanField(default=True)),
                ('funcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocupacoes', to='gestao_projetos.funcaoinstitucional', verbose_name='Função Institucional')),
                ('pessoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocupacoes_funcao', to='cadastros.pessoafisica', verbose_name='Pessoa Física')),
            ],
            options={
                'verbose_name': 'Ocupação de Função',
                'verbose_name_plural': 'Ocupações de Funções',
                'ordering': ['funcao', 'prioridade'],
                'unique_together': {('funcao', 'prioridade')},
            },
        ),
        migrations.CreateModel(
            name='AfastamentoExercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data de Início do Afastamento')),
                ('data_fim', models.DateField(verbose_name='Data de Fim do Afastamento')),
                ('motivo', models.CharField(choices=[('FERIAS', 'Férias'), ('LICENCA_MEDICA', 'Licença Médica'), ('MISSAO', 'Missão Institucional'), ('LICENCA_CAPACITACAO', 'Licença para Capacitação'), ('OUTRO', 'Outro')], default='FERIAS', max_length=25, verbose_name='Motivo')),
                ('documento_comprobatorio', models.CharField(blank=True, help_text='Número da portaria, memorando ou despacho autorizando o afastamento.', max_length=200, verbose_name='Documento Comprobatório')),
                ('ativo', models.BooleanField(default=True)),
                ('ocupacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='afastamentos', to='gestao_projetos.ocupacaofuncao', verbose_name='Ocupação')),
            ],
            options={
                'verbose_name': 'Afastamento de Exercício',
                'verbose_name_plural': 'Afastamentos de Exercício',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='RegraAlcadaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('OFICIO_EQUIPE', 'Ofício de Pagamento da Equipe'), ('OFICIO_COORDENADOR', 'Ofício de Pagamento do Coordenador'), ('OFICIO_COORD_DIRETOR_CAMPUS', 'Ofício de Pagamento do Coordenador (Diretor de Campus)'), ('CONTRATACAO_BOLSISTA', 'Contratação de Bolsista'), ('OUTRO', 'Outro')], max_length=35, verbose_name='Tipo do Documento')),
                ('condicao_beneficiario', models.CharField(choices=[('QUALQUER_BOLSISTA', 'Qualquer Bolsista'), ('COORDENADOR_PROJETO', 'Coordenador do Projeto (não Diretor de Campus)'), ('COORDENADOR_E_DIRETOR_CAMPUS', 'Coordenador que é Diretor-Geral de Campus')], default='QUALQUER_BOLSISTA', max_length=35, verbose_name='Condição do Beneficiário')),
                ('exige_siape', models.BooleanField(default=True, verbose_name='Exige SIAPE do Signatário?')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição / Justificativa Legal')),
                ('ativo', models.BooleanField(default=True)),
                ('funcao_requisitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regras_como_requisitante', to='gestao_projetos.funcaoinstitucional', verbose_name='Função do Signatário Requisitante')),
                ('funcao_visto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regras_como_visto', to='gestao_projetos.funcaoinstitucional', verbose_name='Função do Visto (Ciência)')),
            ],
            options={
                'verbose_name': 'Regra de Alçada de Documento',
                'verbose_name_plural': 'Regras de Alçada de Documentos',
                'ordering': ['tipo_documento', 'condicao_beneficiario'],
                'unique_together': {('tipo_documento', 'condicao_beneficiario')},
            },
        ),
        migrations.RunPython(seed_funcoes_e_ocupacoes, migrations.RunPython.noop),
    ]

