# Generated by Django 6.0.7 on 2026-07-30 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_rename_processo_projetopdi_processo_bolsistaprojeto_and_more'),
        ('gestao_projetos', '0002_remove_convenio_instituicao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorioatividade',
            name='bolsista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_bolsista', to='cadastros.bolsistaprojeto'),
        ),
        migrations.AlterUniqueTogether(
            name='membroequipe',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='membroequipe',
            name='projeto',
        ),
        migrations.RemoveField(
            model_name='membroequipe',
            name='usuario',
        ),
        migrations.AddField(
            model_name='relatorioatividade',
            name='cumpriu_carga_horaria',
            field=models.BooleanField(default=True, verbose_name='Cumpriu com a Carga Horária'),
        ),
        migrations.AddField(
            model_name='relatorioatividade',
            name='parecer_coordenador',
            field=models.TextField(blank=True, null=True, verbose_name='Demais informações pertinentes (Parecer)'),
        ),
        migrations.AlterField(
            model_name='itematividade',
            name='carga_horaria_percentual',
            field=models.CharField(default='100%', max_length=20, verbose_name='Carga Horária / %'),
        ),
        migrations.AlterField(
            model_name='itematividade',
            name='descricao',
            field=models.TextField(verbose_name='Descrição das Atividades'),
        ),
        migrations.AlterField(
            model_name='itematividade',
            name='numero_atividade',
            field=models.CharField(max_length=20, verbose_name='Item/Atividade'),
        ),
        migrations.AlterField(
            model_name='itematividade',
            name='periodo_execucao',
            field=models.CharField(max_length=100, verbose_name='Período de Execução'),
        ),
        migrations.AlterField(
            model_name='relatorioatividade',
            name='carga_horaria_periodo',
            field=models.PositiveIntegerField(verbose_name='Carga Horária do Período'),
        ),
        migrations.AlterField(
            model_name='relatorioatividade',
            name='macroentrega',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ref. Macro Entrega'),
        ),
        migrations.AlterField(
            model_name='relatorioatividade',
            name='parcela',
            field=models.PositiveIntegerField(verbose_name='Número da Parcela'),
        ),
        migrations.AlterField(
            model_name='relatorioatividade',
            name='periodo_fim',
            field=models.DateField(verbose_name='Período Fim'),
        ),
        migrations.AlterField(
            model_name='relatorioatividade',
            name='periodo_inicio',
            field=models.DateField(verbose_name='Período Início'),
        ),
        migrations.DeleteModel(
            name='Bolsista',
        ),
        migrations.DeleteModel(
            name='MembroEquipe',
        ),
    ]
