# Generated by Django 6.0.7 on 2026-09-04 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_projetos', '0003_governanca_alcadas_e_suplencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorioatividade',
            name='atestado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relatorios_atestados', to=settings.AUTH_USER_MODEL, verbose_name='Atestado por (Servidor Efetivo)'),
        ),
        migrations.AddField(
            model_name='relatorioatividade',
            name='data_atesto',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora do Atesto'),
        ),
        migrations.AddField(
            model_name='relatorioatividade',
            name='siape_atesto',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Matrícula SIAPE do Servidor Atestante'),
        ),
    ]
