# Generated by Django 6.0.7 on 2026-07-30 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0011_projetopdi_arquivo_plano_trabalho_atividadeplanoacao'),
        ('gestao_projetos', '0003_alter_relatorioatividade_bolsista_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itematividade',
            options={},
        ),
        migrations.RemoveField(
            model_name='itematividade',
            name='numero_atividade',
        ),
        migrations.AddField(
            model_name='itematividade',
            name='atividade_mae',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tarefas_executadas', to='cadastros.atividadeplanoacao'),
        ),
        migrations.AlterField(
            model_name='itematividade',
            name='carga_horaria_percentual',
            field=models.CharField(default='100%', max_length=10),
        ),
        migrations.AlterField(
            model_name='itematividade',
            name='descricao',
            field=models.TextField(verbose_name='Descrição da Tarefa Realizada'),
        ),
        migrations.AlterField(
            model_name='itematividade',
            name='periodo_execucao',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterModelTable(
            name='itematividade',
            table=None,
        ),
    ]
