# Generated by Django 6.0.7 on 2026-07-31 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0022_cotabolsapt_atividades_vinculadas'),
        ('gestao_projetos', '0004_alter_itematividade_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='relatorioatividade',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='relatorioatividade',
            name='termo_bolsa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_termo', to='cadastros.termobolsa'),
        ),
        migrations.AddField(
            model_name='relatorioatividade',
            name='versao',
            field=models.PositiveIntegerField(default=1, verbose_name='Versão do Relatório'),
        ),
        migrations.AlterField(
            model_name='relatorioatividade',
            name='bolsista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relatorios_bolsista', to='cadastros.bolsistaprojeto'),
        ),
        migrations.AlterUniqueTogether(
            name='relatorioatividade',
            unique_together={('termo_bolsa', 'parcela', 'versao')},
        ),
    ]
