# Generated by Django 6.0.7 on 2026-09-08 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_projetos', '0004_atesto_siape_relatorio_atividade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorioatividade',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Rascunho / Em Elaboração'), ('EM_ANALISE', 'Submetido / Aguardando Atesto SIAPE'), ('CONCLUIDO', 'Homologado / Atestado')], default='PENDENTE', max_length=15),
        ),
    ]
