# Generated by Django 6.0.7 on 2026-08-01 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0026_distribuicaocontacota'),
        ('gestao_projetos', '0005_alter_relatorioatividade_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorioatividade',
            name='conta_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relatorios_pagos', to='cadastros.contabancaria', verbose_name='Conta Pagadora / Fonte de Recurso'),
        ),
    ]
