# Generated by Django 6.0.7 on 2026-08-06 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0027_parcela'),
        ('gestao_projetos', '0006_relatorioatividade_conta_pagamento'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='relatorioatividade',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='relatorioatividade',
            name='parcela_referencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='cadastros.parcela', verbose_name='Parcela de Referência'),
        ),
        migrations.RemoveField(
            model_name='relatorioatividade',
            name='parcela',
        ),
        migrations.AlterUniqueTogether(
            name='relatorioatividade',
            unique_together={('termo_bolsa', 'parcela_referencia', 'versao')},
        ),
    ]
