# Generated by Django 6.0.7 on 2026-08-06 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_projetos', '0007_alter_relatorioatividade_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorioatividade',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Aguardando Assinatura'), ('CONCLUIDO', 'Assinado / Concluído')], default='PENDENTE', max_length=15),
        ),
    ]
