# Generated by Django 6.0.7 on 2026-08-06 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_projetos', '0008_alter_relatorioatividade_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorioatividade',
            name='arquivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='projetos/relatorios_assinados/', verbose_name='Relatório Assinado (PDF)'),
        ),
    ]
