# Generated by Django 6.0.7 on 2026-08-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0032_termobolsa_atualizado_em'),
        ('gestao_projetos', '0009_relatorioatividade_arquivo_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatorioatividade',
            name='macroentrega',
        ),
        migrations.AddField(
            model_name='relatorioatividade',
            name='macroentregas',
            field=models.ManyToManyField(blank=True, related_name='relatorios', to='cadastros.macroentrega', verbose_name='Macroentregas Associadas'),
        ),
    ]
