# Generated by Django 6.0.7 on 2026-08-07 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0032_termobolsa_atualizado_em'),
        ('gestao_projetos', '0010_remove_relatorioatividade_macroentrega_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='relatorioatividade',
            unique_together={('termo_bolsa', 'parcela_referencia')},
        ),
    ]
