# Generated by Django 6.0.4 on 2026-05-19 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFiscalAlmoxarifado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, verbose_name='Número NF-e')),
                ('serie', models.CharField(max_length=10, verbose_name='Série')),
                ('data_emissao', models.DateField(verbose_name='Data de Emissão')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Total da Nota Fiscal')),
                ('fornecedor_cnpj', models.CharField(max_length=20, verbose_name='fornecedor CNPJ')),
                ('fornecedor_nome', models.CharField(max_length=255, verbose_name='fornecedor Nome')),
                ('destinatario_cnpj', models.CharField(max_length=20, verbose_name='Destinatário CNPJ')),
                ('destinatario_nome', models.CharField(max_length=255, verbose_name='Destinatário Nome')),
                ('local_entrega_logradouro', models.CharField(max_length=255, verbose_name='Local de Entrega - Logradouro')),
                ('local_entrega_bairro', models.CharField(max_length=100, verbose_name='Local de Entrega - Bairro')),
                ('local_entrega_municipio', models.CharField(max_length=100, verbose_name='Local de Entrega - Município')),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='almoxarifado/notas/')),
                ('data_importacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Nota Fiscal (Almoxarifado)',
                'verbose_name_plural': 'Notas Fiscais (Almoxarifado)',
                'unique_together': {('numero', 'fornecedor_cnpj')},
            },
        ),
        migrations.CreateModel(
            name='ProdutoAlmoxarifado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_item', models.IntegerField(verbose_name='Num')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Qtd.')),
                ('unidade_comercial', models.CharField(max_length=20, verbose_name='Unidade Comercial')),
                ('valor_unitario', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Valor unitário (R$)')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor (R$)')),
                ('nota_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='almoxarifado.notafiscalalmoxarifado')),
            ],
            options={
                'verbose_name': 'Produto (Almoxarifado)',
                'verbose_name_plural': 'Produtos (Almoxarifado)',
                'ordering': ['numero_item'],
            },
        ),
    ]
