# Generated by Django 6.1.1 on 2026-09-11 20:37

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CotaDiariaIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True, verbose_name='Data de Controle')),
                ('requisicoes_feitas', models.PositiveIntegerField(default=0, verbose_name='Chamadas Executadas')),
                ('limite_diario', models.PositiveIntegerField(default=100, verbose_name='Teto Diário Permitido')),
            ],
            options={
                'verbose_name': 'Cota Diária da IA',
                'verbose_name_plural': 'Cotas Diárias da IA',
            },
        ),
        migrations.CreateModel(
            name='FotoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='almoxarifado/fotos_produtos/', verbose_name='Fotografia do Bem')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrição da Fotografia')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data da Fotografia')),
            ],
            options={
                'verbose_name': 'Foto do Produto',
                'verbose_name_plural': 'Fotos dos Produtos',
            },
        ),
        migrations.CreateModel(
            name='Imposto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=20, unique=True, verbose_name='Sigla do Imposto')),
                ('descricao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descrição')),
                ('esfera', models.CharField(choices=[('FEDERAL', 'Federal'), ('ESTADUAL', 'Estadual'), ('MUNICIPAL', 'Municipal')], max_length=15, verbose_name='Esfera Tributária')),
            ],
        ),
        migrations.CreateModel(
            name='NotaFiscalAlmoxarifado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, verbose_name='Número NF-e')),
                ('serie', models.CharField(max_length=10, verbose_name='Série')),
                ('data_emissao', models.DateField(verbose_name='Data de Emissão')),
                ('data_importacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Importação no Sistema')),
                ('valor_total_produtos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Valor Total dos Produtos')),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Desconto Aplicado')),
                ('valor_total_nota', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Valor Total da Nota')),
                ('valor_frete', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12, verbose_name='Valor do Frete')),
                ('destinatario_nome', models.CharField(max_length=255, verbose_name='Razão Social Destinatário')),
                ('destinatario_cnpj', models.CharField(max_length=20, verbose_name='CNPJ Destinatário')),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='almoxarifado/nfe/', verbose_name='Arquivo Digital (PDF/XML)')),
                ('termo_recebimento_assinado', models.FileField(blank=True, null=True, upload_to='almoxarifado/termos_assinados/', verbose_name='Termo de Recebimento Assinado (PDF)')),
                ('chave_acesso', models.CharField(blank=True, max_length=44, null=True, verbose_name='Chave de Acesso Sefaz')),
                ('data_recebimento', models.DateField(blank=True, null=True, verbose_name='Data de Recebimento Físico')),
            ],
            options={
                'verbose_name': 'Nota Fiscal de Entrada',
                'verbose_name_plural': 'Notas Fiscais de Entrada',
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vinculo', models.CharField(choices=[('SERVIDOR', 'Servidor Público'), ('TERCEIRIZADO', 'Colaborador Terceirizado')], default='SERVIDOR', max_length=20, verbose_name='Tipo de Vínculo')),
                ('siape', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Matrícula SIAPE')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo / Função')),
                ('lotacao', models.CharField(default='Polo de Inovação Manaus', max_length=100, verbose_name='Lotação')),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
            },
        ),
        migrations.CreateModel(
            name='ProdutoAlmoxarifado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_item', models.PositiveIntegerField(verbose_name='Nº do Item')),
                ('descricao', models.TextField(verbose_name='Descrição do Produto/Insumo')),
                ('categoria', models.CharField(choices=[('CONSUMO', 'Consumo'), ('PERMANENTE', 'Bem Permanente'), ('SERVICO', 'Serviço / Outros')], default='CONSUMO', max_length=20, verbose_name='Classificação Patrimonial')),
                ('quantidade', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Quantidade Entregue')),
                ('unidade_comercial', models.CharField(max_length=10, verbose_name='Unidade de Medida')),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Valor Unitário')),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Valor Total do Item')),
            ],
            options={
                'verbose_name': 'Material Cadastrado',
                'verbose_name_plural': 'Materiais Cadastrados',
            },
        ),
        migrations.CreateModel(
            name='TermoRME',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_termo', models.CharField(help_text='Ex: RME-2026/001', max_length=20, unique=True, verbose_name='Número do RME')),
                ('processo_sei', models.CharField(blank=True, max_length=30, null=True, verbose_name='Processo SEI Associado')),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('data_ateste', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('AGUARDANDO_CONFERENCIA', 'Aguardando Conferência Física'), ('DIVERGENTE', 'Divergência Encontrada'), ('ATESTADO', 'Atestado (Recebido)')], default='AGUARDANDO_CONFERENCIA', max_length=25)),
                ('observacoes', models.TextField(blank=True, help_text='Anotações sobre avarias ou divergências na entrega.', null=True)),
            ],
            options={
                'verbose_name': 'Termo de Recebimento (RME)',
                'verbose_name_plural': 'Termos de Recebimento (RME)',
                'ordering': ['-data_geracao'],
            },
        ),
        migrations.CreateModel(
            name='ImpostoNota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Valor do Imposto')),
                ('imposto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_vinculadas', to='almoxarifado.imposto')),
            ],
        ),
    ]
