# Generated by Django 6.1.1 on 2026-09-11 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almoxarifado', '0001_initial'),
        ('cadastros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscalalmoxarifado',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas_almoxarifado', to='cadastros.fornecedor', verbose_name='Fornecedor Oficial'),
        ),
        migrations.AddField(
            model_name='notafiscalalmoxarifado',
            name='projeto_vinculado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_fiscais_almoxarifado', to='cadastros.projetopdi', verbose_name='Projeto PDI de Destino'),
        ),
        migrations.AddField(
            model_name='notafiscalalmoxarifado',
            name='usuario_recebedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_recebidas', to=settings.AUTH_USER_MODEL, verbose_name='Servidor/Colaborador que Recebeu'),
        ),
        migrations.AddField(
            model_name='impostonota',
            name='nota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tributos_reais', to='almoxarifado.notafiscalalmoxarifado'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='produtoalmoxarifado',
            name='nota_fiscal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='almoxarifado.notafiscalalmoxarifado', verbose_name='Nota Fiscal Origem'),
        ),
        migrations.AddField(
            model_name='fotoproduto',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='almoxarifado.produtoalmoxarifado', verbose_name='Produto Associado'),
        ),
        migrations.AddField(
            model_name='termorme',
            name='nota_fiscal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='termo_rme', to='almoxarifado.notafiscalalmoxarifado'),
        ),
        migrations.AddField(
            model_name='termorme',
            name='servidor_conferente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rmes_conferidos', to=settings.AUTH_USER_MODEL, verbose_name='Servidor Conferente (SIAPE)'),
        ),
        migrations.AlterUniqueTogether(
            name='notafiscalalmoxarifado',
            unique_together={('numero', 'fornecedor')},
        ),
    ]
