# Generated by Django 6.0.4 on 2026-05-19 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtoalmoxarifado',
            name='categoria',
            field=models.CharField(choices=[('CONSUMO', 'Material de Consumo (Insumos, Papel, Peças)'), ('PERMANENTE', 'Bem Móvel / Permanente (Equipamentos, Ferramentas, Mobília)'), ('SERVICO', 'Serviço Prestado'), ('OUTROS', 'Não Classificado')], default='OUTROS', max_length=20, verbose_name='Classificação Contábil'),
        ),
    ]
