# Generated by Django 6.0.4 on 2026-05-19 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0002_produtoalmoxarifado_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='almoxarifado/fotos_produtos/', verbose_name='Fotografia')),
                ('descricao', models.CharField(blank=True, help_text='Ex: Etiqueta de Patrimônio, Número de Série, Visão Geral', max_length=255, null=True)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='almoxarifado.produtoalmoxarifado')),
            ],
            options={
                'verbose_name': 'Foto do Produto',
                'verbose_name_plural': 'Fotos dos Produtos',
            },
        ),
    ]
