# Generated by Django 6.0.4 on 2026-05-20 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0003_fotoproduto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notafiscalalmoxarifado',
            name='local_entrega_bairro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Local de Entrega - Bairro'),
        ),
        migrations.AlterField(
            model_name='notafiscalalmoxarifado',
            name='local_entrega_logradouro',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Local de Entrega - Logradouro'),
        ),
        migrations.AlterField(
            model_name='notafiscalalmoxarifado',
            name='local_entrega_municipio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Local de Entrega - Município'),
        ),
    ]
