# Generated by Django 6.0.4 on 2026-05-20 16:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0004_alter_notafiscalalmoxarifado_local_entrega_bairro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CotaDiariaIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.localdate, unique=True, verbose_name='Data da Cota')),
                ('requisicoes_feitas', models.IntegerField(default=0)),
                ('limite_diario', models.IntegerField(default=120)),
            ],
            options={
                'verbose_name': 'Cota Diária da IA',
                'verbose_name_plural': 'Cotas Diárias da IA',
            },
        ),
    ]
