# Generated by Django 6.0.4 on 2026-05-20 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0005_cotadiariaia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siape', models.CharField(max_length=15, unique=True, verbose_name='Matrícula SIAPE')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo / Função')),
                ('lotacao', models.CharField(default='Polo de Inovação Manaus', max_length=100, verbose_name='Lotação')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
