# Generated by Django 6.0.4 on 2026-05-20 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0006_perfilusuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notafiscalalmoxarifado',
            options={'verbose_name': 'Nota Fiscal de Entrada', 'verbose_name_plural': 'Notas Fiscais de Entrada'},
        ),
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'verbose_name': 'Perfil de Usuário', 'verbose_name_plural': 'Perfis de Usuários'},
        ),
        migrations.AlterModelOptions(
            name='produtoalmoxarifado',
            options={'verbose_name': 'Material Cadastrado', 'verbose_name_plural': 'Materiais Cadastrados'},
        ),
        migrations.RemoveField(
            model_name='fotoproduto',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='notafiscalalmoxarifado',
            name='local_entrega_bairro',
        ),
        migrations.RemoveField(
            model_name='notafiscalalmoxarifado',
            name='local_entrega_logradouro',
        ),
        migrations.RemoveField(
            model_name='notafiscalalmoxarifado',
            name='local_entrega_municipio',
        ),
        migrations.AddField(
            model_name='notafiscalalmoxarifado',
            name='chave_acesso',
            field=models.CharField(blank=True, max_length=44, null=True, verbose_name='Chave de Acesso Sefaz'),
        ),
        migrations.AddField(
            model_name='notafiscalalmoxarifado',
            name='data_recebimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Recebimento Físico'),
        ),
        migrations.AddField(
            model_name='notafiscalalmoxarifado',
            name='usuario_recebedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_recebidas', to=settings.AUTH_USER_MODEL, verbose_name='Servidor que Recebeu o Material'),
        ),
        migrations.AlterField(
            model_name='cotadiariaia',
            name='data',
            field=models.DateField(unique=True, verbose_name='Data de Controle'),
        ),
        migrations.AlterField(
            model_name='cotadiariaia',
            name='limite_diario',
            field=models.PositiveIntegerField(default=100, verbose_name='Teto Diário Permitido'),
        ),
        migrations.AlterField(
            model_name='cotadiariaia',
            name='requisicoes_feitas',
            field=models.PositiveIntegerField(default=0, verbose_name='Chamadas Executadas'),
        ),
        migrations.AlterField(
            model_name='fotoproduto',
            name='data_upload',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data da Fotografia'),
        ),
        migrations.AlterField(
            model_name='fotoproduto',
            name='imagem',
            field=models.ImageField(upload_to='almoxarifado/fotos_produtos/', verbose_name='Fotografia do Bem'),
        ),
        migrations.AlterField(
            model_name='fotoproduto',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='almoxarifado.produtoalmoxarifado', verbose_name='Produto Associado'),
        ),
        migrations.AlterField(
            model_name='notafiscalalmoxarifado',
            name='arquivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='almoxarifado/nfe/', verbose_name='Arquivo Digital (PDF/XML)'),
        ),
        migrations.AlterField(
            model_name='notafiscalalmoxarifado',
            name='data_importacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Importação no Sistema'),
        ),
        migrations.AlterField(
            model_name='notafiscalalmoxarifado',
            name='destinatario_cnpj',
            field=models.CharField(max_length=20, verbose_name='CNPJ Destinatário'),
        ),
        migrations.AlterField(
            model_name='notafiscalalmoxarifado',
            name='destinatario_nome',
            field=models.CharField(max_length=255, verbose_name='Razão Social Destinatário'),
        ),
        migrations.AlterField(
            model_name='notafiscalalmoxarifado',
            name='fornecedor_cnpj',
            field=models.CharField(max_length=20, verbose_name='CNPJ Fornecedor'),
        ),
        migrations.AlterField(
            model_name='notafiscalalmoxarifado',
            name='fornecedor_nome',
            field=models.CharField(max_length=255, verbose_name='Razão Social Fornecedor'),
        ),
        migrations.AlterField(
            model_name='notafiscalalmoxarifado',
            name='numero',
            field=models.CharField(max_length=20, verbose_name='Número NF-e'),
        ),
        migrations.AlterField(
            model_name='notafiscalalmoxarifado',
            name='valor_total',
            field=models.FloatField(verbose_name='Valor Total da Nota'),
        ),
        migrations.AlterField(
            model_name='produtoalmoxarifado',
            name='categoria',
            field=models.CharField(choices=[('CONSUMO', 'Consumo'), ('PERMANENTE', 'Bem Permanente'), ('SERVICO', 'Serviço / Outros')], default='CONSUMO', max_length=20, verbose_name='Classificação Patrimonial'),
        ),
        migrations.AlterField(
            model_name='produtoalmoxarifado',
            name='descricao',
            field=models.TextField(verbose_name='Descrição do Produto/Insumo'),
        ),
        migrations.AlterField(
            model_name='produtoalmoxarifado',
            name='nota_fiscal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='almoxarifado.notafiscalalmoxarifado', verbose_name='Nota Fiscal Origem'),
        ),
        migrations.AlterField(
            model_name='produtoalmoxarifado',
            name='numero_item',
            field=models.PositiveIntegerField(verbose_name='Nº do Item'),
        ),
        migrations.AlterField(
            model_name='produtoalmoxarifado',
            name='quantidade',
            field=models.FloatField(verbose_name='Quantidade Entregue'),
        ),
        migrations.AlterField(
            model_name='produtoalmoxarifado',
            name='unidade_comercial',
            field=models.CharField(max_length=10, verbose_name='Unidade de Medida'),
        ),
        migrations.AlterField(
            model_name='produtoalmoxarifado',
            name='valor_total',
            field=models.FloatField(verbose_name='Valor Total do Item'),
        ),
        migrations.AlterField(
            model_name='produtoalmoxarifado',
            name='valor_unitario',
            field=models.FloatField(verbose_name='Valor Unitário'),
        ),
    ]
