# Generated by Django 6.0.4 on 2026-05-20 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0007_alter_notafiscalalmoxarifado_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='vinculo',
            field=models.CharField(choices=[('SERVIDOR', 'Servidor Público'), ('TERCEIRIZADO', 'Colaborador Terceirizado')], default='SERVIDOR', max_length=20, verbose_name='Tipo de Vínculo'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='siape',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Matrícula SIAPE'),
        ),
    ]
