# Generated by Django 6.0.4 on 2026-05-20 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0008_perfilusuario_cpf_perfilusuario_vinculo_and_more'),
        ('cadastros', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscalalmoxarifado',
            name='projeto_vinculado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_fiscais_almoxarifado', to='cadastros.projetopdi', verbose_name='Projeto PDI de Destino'),
        ),
        migrations.AlterField(
            model_name='notafiscalalmoxarifado',
            name='usuario_recebedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_recebidas', to=settings.AUTH_USER_MODEL, verbose_name='Servidor/Colaborador que Recebeu'),
        ),
    ]
