# Generated by Django 6.0.4 on 2026-05-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0009_notafiscalalmoxarifado_projeto_vinculado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotoproduto',
            name='descricao',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrição da Fotografia'),
        ),
    ]
