# Generated by Django 6.0.4 on 2026-06-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0010_fotoproduto_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscalalmoxarifado',
            name='termo_recebimento_assinado',
            field=models.FileField(blank=True, null=True, upload_to='almoxarifado/termos_assinados/', verbose_name='Termo de Recebimento Assinado (PDF)'),
        ),
    ]
