# Generated by Django 6.0.4 on 2026-06-01 19:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0011_notafiscalalmoxarifado_termo_recebimento_assinado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notafiscalalmoxarifado',
            name='valor_total',
        ),
        migrations.AddField(
            model_name='notafiscalalmoxarifado',
            name='valor_desconto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Desconto Aplicado'),
        ),
        migrations.AddField(
            model_name='notafiscalalmoxarifado',
            name='valor_total_nota',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Valor Total da Nota'),
        ),
        migrations.AddField(
            model_name='notafiscalalmoxarifado',
            name='valor_total_produtos',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Valor Total dos Produtos'),
        ),
    ]
