# Generated by Django 6.0.4 on 2026-06-01 22:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0012_remove_notafiscalalmoxarifado_valor_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtoalmoxarifado',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Quantidade Entregue'),
        ),
        migrations.AlterField(
            model_name='produtoalmoxarifado',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Valor Total do Item'),
        ),
        migrations.AlterField(
            model_name='produtoalmoxarifado',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Valor Unitário'),
        ),
    ]
