# Generated by Django 6.0.4 on 2026-06-11 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0013_alter_produtoalmoxarifado_quantidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imposto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=20, unique=True, verbose_name='Sigla do Imposto')),
                ('descricao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descrição')),
                ('esfera', models.CharField(choices=[('FEDERAL', 'Federal'), ('ESTADUAL', 'Estadual'), ('MUNICIPAL', 'Municipal')], max_length=15, verbose_name='Esfera Tributária')),
            ],
        ),
        migrations.AddField(
            model_name='notafiscalalmoxarifado',
            name='valor_frete',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Valor do Frete'),
        ),
        migrations.CreateModel(
            name='ImpostoNota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Valor do Imposto')),
                ('imposto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_vinculadas', to='almoxarifado.imposto')),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tributos_reais', to='almoxarifado.notafiscalalmoxarifado')),
            ],
        ),
    ]
