# Generated by Django 6.0.4 on 2026-06-19 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0014_imposto_notafiscalalmoxarifado_valor_frete_and_more'),
        ('cadastros', '0005_projetopdi_projeto_alter_projetopdi_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscalalmoxarifado',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas_almoxarifado', to='cadastros.fornecedor', verbose_name='Fornecedor Oficial'),
        ),
    ]
