# Generated by Django 6.0.4 on 2026-06-19 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0015_notafiscalalmoxarifado_fornecedor'),
        ('cadastros', '0006_convenio_instituicaoparceira_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notafiscalalmoxarifado',
            unique_together={('numero', 'fornecedor')},
        ),
        migrations.RemoveField(
            model_name='notafiscalalmoxarifado',
            name='fornecedor_cnpj',
        ),
        migrations.RemoveField(
            model_name='notafiscalalmoxarifado',
            name='fornecedor_nome',
        ),
    ]
