# Generated by Django 6.0.4 on 2026-07-07 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0016_alter_notafiscalalmoxarifado_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TermoRME',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_termo', models.CharField(help_text='Ex: RME-2026/001', max_length=20, unique=True, verbose_name='Número do RME')),
                ('processo_sei', models.CharField(blank=True, max_length=30, null=True, verbose_name='Processo SEI Associado')),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('data_ateste', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('AGUARDANDO_CONFERENCIA', 'Aguardando Conferência Física'), ('DIVERGENTE', 'Divergência Encontrada'), ('ATESTADO', 'Atestado (Recebido)')], default='AGUARDANDO_CONFERENCIA', max_length=25)),
                ('observacoes', models.TextField(blank=True, help_text='Anotações sobre avarias ou divergências na entrega.', null=True)),
                ('nota_fiscal', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='termo_rme', to='almoxarifado.notafiscalalmoxarifado')),
                ('servidor_conferente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rmes_conferidos', to=settings.AUTH_USER_MODEL, verbose_name='Servidor Conferente (SIAPE)')),
            ],
            options={
                'verbose_name': 'Termo de Recebimento (RME)',
                'verbose_name_plural': 'Termos de Recebimento (RME)',
                'ordering': ['-data_geracao'],
            },
        ),
    ]
