# Generated by Django 6.0.4 on 2026-08-02 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao_predial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Categoria de Serviço',
                'verbose_name_plural': 'Categorias de Serviço',
            },
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='tipo_manutencao',
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='manutencao_predial.categoriaservico', verbose_name='Categoria'),
        ),
    ]
