# Generated by Django 6.0.4 on 2026-08-02 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao_predial', '0002_categoriaservico_remove_ordemservico_tipo_manutencao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='estoque_baixado',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='os_solicitadas', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante'),
        ),
    ]
