# Generated by Django 6.1.1 on 2026-09-11 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
        ('central_servicos', '0001_initial'),
        ('incorporacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiltroImportacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo', models.CharField(max_length=255, unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='VerificacaoTermo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_termo', models.CharField(blank=True, max_length=255, null=True)),
                ('termo_pdf', models.FileField(upload_to='termos_conferencia/')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente (Novo)'), ('EM_CONFERENCIA', 'Em Conferência'), ('VALIDADO', 'Validado (Aguardando Aprovação)'), ('APROVADO', 'Aprovado (No Inventário)')], default='PENDENTE', max_length=20)),
                ('dados_brutos', models.JSONField(blank=True, null=True)),
                ('linhas_cabecalho', models.IntegerField(default=5)),
                ('linha_atual', models.IntegerField(default=0)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('projeto_em_memoria', models.CharField(blank=True, max_length=255, null=True)),
                ('conta_em_memoria', models.CharField(blank=True, max_length=50, null=True)),
                ('dv_em_memoria', models.CharField(blank=True, max_length=5, null=True)),
                ('documento_em_memoria', models.CharField(blank=True, max_length=255, null=True)),
                ('situacao_em_memoria', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BemPatrimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patrimonio_ifam', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('patrimonio_doador', models.CharField(blank=True, max_length=50, null=True)),
                ('descricao', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('nota_fiscal', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_conservacao', models.CharField(choices=[('NOVO', 'Novo'), ('BOM', 'Bom'), ('OCIOSO', 'Ocioso'), ('RECUPERAVEL', 'Recuperável'), ('IRRECUPERAVEL', 'Irrecuperável')], default='NOVO', max_length=20)),
                ('status_operacional', models.CharField(default='ATIVO', max_length=20)),
                ('data_incorporacao', models.DateTimeField(auto_now_add=True)),
                ('ambiente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bens_patrimoniais', to='central_servicos.ambiente', verbose_name='Ambiente (Localização)')),
                ('conta_bancaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bens_patrimoniais', to='cadastros.contabancaria', verbose_name='Conta Bancária Pagadora')),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.projetopdi')),
                ('termo_doacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bens_patrimoniais', to='incorporacao.termodoacao')),
            ],
        ),
        migrations.CreateModel(
            name='ItemVerificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ativo', models.CharField(default='pendente', max_length=50)),
                ('descricao', models.TextField(default='pendente')),
                ('processo_compra', models.CharField(default='pendente', max_length=100)),
                ('processo_pagamento', models.CharField(default='pendente', max_length=100)),
                ('cnpj_cpf_fornecedor', models.CharField(default='pendente', max_length=50)),
                ('nome_fornecedor', models.CharField(default='pendente', max_length=255)),
                ('nota_fiscal', models.CharField(default='pendente', max_length=100)),
                ('data_nf', models.CharField(default='pendente', max_length=50)),
                ('valor_bem', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('conta', models.CharField(default='pendente', max_length=50)),
                ('dv', models.CharField(default='pendente', max_length=10)),
                ('projeto', models.CharField(default='pendente', max_length=100)),
                ('localizacao', models.CharField(default='pendente', max_length=255)),
                ('situacao', models.CharField(default='pendente', max_length=100)),
                ('data_movimentacao', models.CharField(default='pendente', max_length=50)),
                ('documento', models.CharField(default='pendente', max_length=255)),
                ('erro_leitura', models.BooleanField(default=False)),
                ('validado_por_usuario', models.BooleanField(default=False)),
                ('verificacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='patrimonio.verificacaotermo')),
            ],
        ),
    ]
