# Generated by Django 6.0.4 on 2026-06-19 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_convenio_instituicaoparceira_and_more'),
        ('incorporacao', '0001_initial'),
        ('patrimonio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bempatrimonial',
            name='projeto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.projetopdi'),
        ),
        migrations.AlterField(
            model_name='bempatrimonial',
            name='termo_doacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bens_patrimoniais', to='incorporacao.termodoacao'),
        ),
        migrations.DeleteModel(
            name='ProjetoPDI',
        ),
        migrations.DeleteModel(
            name='TermoDoacao',
        ),
    ]
