# Generated by Django 6.0.7 on 2026-08-12 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0032_termobolsa_atualizado_em'),
        ('central_servicos', '0010_categoriaelemento_tipoambiente_and_more'),
        ('incorporacao', '0001_initial'),
        ('patrimonio', '0002_alter_bempatrimonial_projeto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bempatrimonial',
            name='ambiente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bens_patrimoniais', to='central_servicos.ambiente', verbose_name='Ambiente (Localização)'),
        ),
        migrations.AlterField(
            model_name='bempatrimonial',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.projetopdi'),
        ),
        migrations.AlterField(
            model_name='bempatrimonial',
            name='termo_doacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bens_patrimoniais', to='incorporacao.termodoacao'),
        ),
    ]
