# Generated by Django 6.0.7 on 2026-09-07 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0066_processo_conta_bancaria'),
        ('patrimonio', '0003_bempatrimonial_ambiente_alter_bempatrimonial_projeto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bempatrimonial',
            name='conta_bancaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bens_patrimoniais', to='cadastros.contabancaria', verbose_name='Conta Bancária Pagadora'),
        ),
    ]
