# Generated by Django 6.0.4 on 2026-05-19 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermoDoacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, verbose_name='Número do Documento')),
                ('ano', models.CharField(max_length=4, verbose_name='Ano')),
                ('data', models.DateField(verbose_name='Data de Formalização')),
                ('objeto', models.TextField(blank=True, help_text='O robô ARGUS extrairá este texto automaticamente do PDF.', null=True, verbose_name='Objeto da Doação')),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='termos_doacao/')),
                ('dados_brutos', models.JSONField(blank=True, null=True)),
                ('data_importacao', models.DateTimeField(auto_now_add=True)),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.origemdoacao', verbose_name='Entidade de Origem')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='termos', to='cadastros.projetopdi')),
            ],
            options={
                'verbose_name': 'Termo de Doação',
                'verbose_name_plural': 'Termos de Doação',
            },
        ),
        migrations.CreateModel(
            name='ItemPatrimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ativo', models.CharField(max_length=50, verbose_name='Nº Patrimônio')),
                ('descricao', models.TextField(verbose_name='Descrição do Bem')),
                ('valor_bem', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor Unitário')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('localizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_alocados', to='cadastros.localizacao', verbose_name='Localização Destino')),
                ('nota_fiscal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_vinculados', to='cadastros.notafiscal', verbose_name='Nota Fiscal')),
                ('processo_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_comprados', to='cadastros.processo', verbose_name='Processo de Compra')),
                ('processos_pagamento', models.ManyToManyField(related_name='itens_pagos', to='cadastros.processo', verbose_name='Processos de Pagamento')),
                ('termo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_patrimoniais', to='incorporacao.termodoacao')),
            ],
            options={
                'verbose_name': 'Item Patrimonial',
                'verbose_name_plural': 'Itens Patrimoniais',
            },
        ),
    ]
