# Generated by Django 6.0.7 on 2026-09-07 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incorporacao', '0002_itempatrimonial_conta_bancaria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempatrimonial',
            name='conta_bancaria',
        ),
    ]
