# Generated by Django 6.0.7 on 2026-09-07 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0066_processo_conta_bancaria'),
        ('incorporacao', '0003_remove_itempatrimonial_conta_bancaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempatrimonial',
            name='conta_bancaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_patrimoniais', to='cadastros.contabancaria', verbose_name='Conta Bancária de Débito'),
        ),
    ]
